---
title: "Incentives for Public Goods Inside Organizations: Field Experimental Evidence"

thanks: "Blasco: Harvard Institute for Quantitative Social Science, Harvard University, 1737 Cambridge Street, Cambridge, MA 02138 (email: ablasco@fas.harvard.edu). Jung: Harvard Business School, Soldiers Field, Boston, MA 02163 (email: ojung@hbs.edu), Lakhani: Harvard Business School, Soldiers Field, Boston, MA 02163, and National Bureau of Economic Research (email: k@hbs.edu). Menietti: Harvard Institute for Quantitative Social Science, Harvard University, 1737 Cambridge Street, Cambridge, MA 02138 (email: mmenietti@fas.harvard.edu). We gratefully acknowledge the financial support of the MacArthur Foundation (Opening Governance Network), NASA Tournament Lab, and the Harvard Business School Division of Faculty Research and Development.  This project would not have been possible without the support of Eric Isselbacher, Julia Jackson, Maulik Majmudar and Perry Band from the Massachusetts General Hospital's Healthcare Transformation Lab."

date: "Last updated: `r format(Sys.time(), '%d %B, %Y')`"

author: 
    - Andrea Blasco
    - Olivia S. Jung
    - Karim R. Lakhani
    - Michael Menietti

abstract: "We report results of a natural field experiment conducted at a medical organization that held an innovation contest seeking contribution of public goods (i.e., projects for organizational improvement) from its more than 1200 employees. We find that offering a prize for winning submissions boosted participation by 85 percent ($+2.5$ percentage points) without affecting the quality of the submissions. The effect was consistent across gender and job type. We posit that the allure of a prize, in combination with mission-oriented preferences, drove participation. Using a simple model, we estimate that these preferences explain about a third of the magnitude of the effect. We also find that these results were sensitive to the solicited person's gender. Overall, because the incentive effect of offering a prize for winning the contest interacts with prosocial motivations of workers to contribute to the public good, prizes appear to be a more profitable way for firms to encourage contribution to public goods from their workers than currently acknowledged in the traditional tournament theory literature."

JEL: 
  - H41
  - D23
  - D03

keywords: 
  - innovation contest
  - free rider problem
  - social preferences
  - altruism
  - idea generation
  - organization of work

endfloat: false

---

```{r, echo=FALSE, warnings=FALSE, message=FALSE}
knitr::opts_chunk$set(
  cache=FALSE,
  echo=FALSE,
  message=FALSE,
  warning=TRUE,
  error=FALSE,
  tidy=FALSE,
  fig.width=5,
  fig.height=5,
  cache.path="Cache/",
  fig.path="Figures/")

source("config.Rmd")
```

```{r child = '1_intro.Rmd'}
```

```{r child = '2_methods.Rmd'}
```

```{r child = '3_results.Rmd'}
```

```{r child = '4_discussion.Rmd'}
```


References
=============
