Introduction
================

Employees divide their time between production tasks tied to pay and promotion and organizational improvements without explicit compensation. This dilemma leads to 
two key issues in the analysis of incentives inside organizations. First, compensation schemes need to address a multitasking problem [@holmstrom1991multitask; @hellmann2011incentives; @manso2011motivating] as time and effort are
more likely to be directed towards the rewarded tasks. Second, the non-rival nature of improvement work that benefits the organization as a whole may tempt workers to free-ride on the efforts of others.

<!-- working on their regular assignment and developing opportunities to improve the workplace. For example, a worker may concentrate on production tasks alone -- with pay and promotion tied to performance in these activities -- or also devote time and energy to solve common organizational problems  -- with no direct compensation for the worker.  -->

<!-- 
This situation leads to two key issues in the analysis of incentives inside organizations. First, there is a problem of designing compensation schemes for employees to take the correct actions by addressing any potential  _multitasking_ issue [@holmstrom1991multitask; @hellmann2011incentives; @manso2011motivating]. Because such opportunities are privately observed, standard incentives may backfire resulting in an inefficient allocation of effort.  Second, there is a _public good contribution_ problem. Because of the non-rival nature of work that benefits the organization as a whole, employees may be tempted to avoid working on these tasks in the hope to free-ride on the efforts of others.
 -->

An organizational contest that seeks contribution of public goods (e.g., suggestion of organizational improvement opportunities) and offers a winning prize may be a proper way to remedy the incentives. Contests stimulate risk taking and participation in less-easily contractible tasks, as discussed by @lazear1981rank; @green1983comparison; @mary1984economic among others. However, <!-- standard contest theory literature does not take into account the non-rival nature of contributing which constitutes the public good contribution problem. --> traditional contest literature does not take into account the non-rival nature of contributing  which constitutes the public good problem. Standard contest theory models presumes that only the contest sponsor (e.g., managers) enjoy the contest outcome, with small gains for the participants beyond the prizes given to the winners.^[One notable exception is the model of tournaments with positive externalities introduced by @drago1988incentive.] This assumption may become questionable when contest participants can expect gains from the work of others, as in the case of a competition aiming at  organizational improvements. The use of contests under these circumstances raises an important question: Are contests an effective incentive mechanism in fostering contributions to public goods inside organizations? <!--  To what extent employees "spontaneously" (without explicit incentives) internalize the need of improvements? -->

In the present study, we report results of a natural field experiment that considers two dominant perspectives on the issue. The first comes from the seminal work of @morgan2000financing, who stresses that awarding prizes in lottery-like contests will mitigate, or even eliminate, the incentive to free ride. At the margin, employees choose their level of effort so that expected gains and costs are equal. Because these gains include direct utility from receiving a prize and from improving their organization, employees' participation is likely to be boosted beyond the pecuniary value of the prize. In the second perspective, employees will volunteer their effort when the contest aim matches the preferences of workers, as discussed by @besley2005competition, @prendergast2007motivation, @delfgaauw2008incentives among others.^[Everyday evidence for this kind of "altruistic" behavior comes from blood donations, charitable giving, social workers. See also the results of laboratory experiments based on economic games [see @levitt2007laboratory] and field studies showing evidence on prosocial preferences at work [@bandiera2005social; @dellavigna2016estimating].] According to this perspective, announcing a competition for prizes can cause unintentional adverse consequences, such as evoking mixed behaviors in workers with varying inclinations towards competition or risk [e.g., men and women @niederle2007women; @croson2009gender]; promoting unethical behavior [@lazear1989pay; @charness2013dark]; weakening intrinsic motivations [@reeve1996elements; @frey1997not]; and even hurting the creativity of innovative work [@erat2015incentives].

We conducted this study in collaboration with the Massachusetts General Hospital's (MGH) Corrigan Minehan Heart Center ("Heart Center"), a prominent medical organization in the United States and a teaching hospital of the Harvard Medical School. The health care delivery context is particularly relevant as the need for organizational improvement and innovation is vastly noted [e.g., @cutler2012reducing]. In addition, health care professionals are commonly seen as willing to step beyond the boundaries of their contractual duties to offer better care [@delfgaauw2005dedicated], which makes the comparison of different incentives towards a public good especially relevant and interesting.  


The Heart Center launched a contest aimed to improve the operations of the organization, in the spirit of "open innovation" discussed in @terwiesch2008innovation, @lakhani2013prize, and @glaeser2016predictive. The contest solicited employees to submit project proposals describing an existing problem and providing a solution to address the problem. After the submission phase, the contest invited all employees to read and rate each proposal on a five-point scale. The winning proposal would receive funding for implementation, implying additional costs and responsibilities from making a winning proposal, such as providing further guidance or a direct involvement in implementation, that were not compensated by winning the competition. Winners of the contest received an iPad mini, the value of which was relatively small in comparison to the foreseeable costs of unpaid proposal implementation time and effort.  <!-- 
clear opportunity for the winners to increase the chances of a promotion  or tenure, which are based on wholly different criteria. -->

The subject pool consisted of over 1,200 staff members of the Heart Center including physicians, nurses, and administrative staff (the entire population). Our main intervention involved altering the content of solicitations: in the PRIZE treatment, the solicitation nudged employees to participate to win an iPad mini; in the FUND treatment, the solicitation nudged employees to participate to win $20,000 towards implementation of the proposal (the submitters would not receive this money for personal use); in the remaining two treatments, we emphasized the opportunity to improve the healthcare of the patients (PCARE) or the workplace (WPLACE). We randomly assigned each Heart Center staff to receive one of the four solicitations. 


By doing so, we obtained causal estimates of the effect of different incentives on two main outcomes: (a) the decision to submit a proposal and engage in an organizational improvement task and (b) the quality of the submissions measured by over 12,000 peer ratings and about 100 evaluations made by the contest organizers. Using data on profession and gender, we also characterized the heterogeneity of responses to the treatment, testing the implications of our intervention for the organization.

<!-- 
We designed four treatments related to our research questions. In a first treatment (PRIZE), the solicitation nudged employees to participate in the initiative by announcing a personal reward (an Apple iPad mini) for the top submissions. In a second treatment (FUND), the solicitation nudged employees with the funding opportunity alone and an explicit commitment by Hearth Center executives to pay expenses up to $20,000 towards implementation of the proposal (the submitters would not receive this money for personal use). In the remaining two treatments, we "framed" the contest by emphasizing the opportunity to improve the healthcare of the patients (PCARE) or the workplace (WPLACE).
 -->

<!-- 
Also, the innovation contest marked the first time for the Heart Center and MGH. So, staff members had no prior experience and learned the opportunity primarily via our individualized communication strategy. Staff members were further asked to make individual submissions, thus helping us to exclude other common mechanisms to raise individual levels of effort, such as peer pressure, peer monitoring, or being part of a team [e.g., @kandel1992peer; @hamilton2003team]. 
 -->

<!-- Results -->
```{r}
submitters  <- hc$num_ideas>0
participants <- ifelse(hc$num_ideas>0 | hc$num_voted_ideas >0, 1, 0)
```

We find a high participation rate despite its cost: `r sum(participants)` employees (`r round(100*mean(participants))` percent) across the entire organization participated in the initiative, with `r round(100*mean(submitters))` percent of our sample submitting a  proposal.^[By comparison, in a purely public good setting such as @list2002effects's field experiment on individual monetary contributions to charity, the authors find very similar participation rates between 3 and 8 percent. Similarly, in a setting that involves employees of a consulting company making proposals to clients with no clear public good incentive, @gibbs2014field finds participation rates that are slightly higher (about 10 percent) but over a two-year period versus our four-week competition.] About half of the participants were invited to submit detailed implementation plans. Two of these submissions received funding for implementation.

We observe that small prizes boosted participation without lowering the quality of the submissions. Mentioning the prize in the solicitation email produced a 2.5 percentage points (85 percent) increase in participation. This effect appears too large for a contest without public good incentives. The relatively high incomes of our subject pool, the low chance of winning, and the anticipated costs of being selected for implementation suggest that very few would find it advantageous to participate. We discuss several possible explanations for this observation and conclude that offering a prize increased participation because it reduced the incentive to free ride, as in @morgan2000financing. We then use a simple model to estimate employees' underlying preferences towards improving the organization (i.e., the public good), showing that these preferences can account for 25 percent of individual costs of participation. 

Analysis of the peer ratings indicates that there was no crowding-out effect. The higher propensity of participation for employees in the PRIZE treatment does not seem to be driven by low-quality submissions. This result is consistent with ratings by the Heart Center managers. We also find small differences in content in terms of the number of  proposals submitted by a participant, areas of focus, and proposal length across treatment groups. Overall, these findings suggest no trade-off between quantity and quality; treatments that attracted more participation resulted in proposals of comparable quality and content. This also implies that monetary incentives were not counter-productive to creativity compared to voluntary contributions.

We find that framing around the mission of the organization resulted in responses that were sensitive to the gender of the solicited person. Women's participation was greater when emphasizing the patient care whereas men's participation was significantly lower, controlling for the profession. At the same time, we do not find gender-based differences with respect to participation in the PRIZE treatment: women's participation was slightly higher but not significant than men's. The first finding suggests that gender may influence sensitivity to framing concerning the organizational mission (i.e., patient care). The second evidence indicates that gender differences in preferences, such as competitive inclinations or risk aversion, may not exert great influence on responses of workers to contests inside organizations.

Finally, employees were less likely to participate when solicited with the funding opportunity alone -- even with a non-trivial amount of $20,000 in implementation funding -- compared to all other treatments. This finding suggests that the opportunity to lead implementation of one's own submitted idea, a non-production task, was not perceived as a reward. 
 
 
<!-- Literature -->

Literature
==========

The present study contributes to the literature on the use of prizes (relative incentives) in the workplace [@lazear1981rank; @green1983comparison; @mary1984economic, among others]. Our main contribution consists in studying the role of prizes in fostering workers' participation in the field and in activities that produce organizational improvements. In particular, the observed increase in participation in the PRIZE treatment is consistent with the results of existing empirical studies [@bull1987tournaments; @knoeber1994testing; @eriksson1999executive; @ehrenberg1990tournaments; @terwiesch2008innovation; @terwiesch2009innovation; @boudreau2011incentives; @boudreau2016performance]. However, while most studies focus on tournaments that result in benefits enjoyed exclusively by the sponsor of the competition (increasing sales, production, revenues), we show that this positive result generalizes to situations that generate positive externalities for the contestants (innovation projects to improve the organization). Despite being a common situation,^[Members of the same organization often end up competing on the basis of their ability to solve common issues at the organizational level, such as addressing specific problems, innovating, providing business ideas.] this setting has received relatively less attention in past studies. 

Our work also contributes to the empirical literature on the use of contest-type lotteries to finance public goods that was first studied by @morgan2000financing. A number of works have shown a positive effect of prizes on the extent of individual contributions to a public good in the laboratory [@morgan2000funding; @dale2004charitable; @lange2007using] and in the field [@landry2006toward]. However, as noted by @vesterlund2012voluntary, the existing evidence on the profitability of contest-type mechanisms for raising money for public goods (e.g., charity donations) is only mixed [@vesterlund2012voluntary]. Our work provides further evidence to this theory as we extend the results of past studies to an organizational setting. Within this setting, individual contributions are non-monetary but consist of time and effort in putting forward (and implementing) a proposal, and the public good consists of the potential improvements for the organization. Under such circumstances, we find evidence indicating that offering prizes can effectively raise the level of participation (compared to voluntary mechanisms) and overall appear to be a profitable solution for organizations.

Our results also relate to the literature on social preferences at work. A number of studies have shown that people tend to contribute to public goods despite strong incentives to free ride. According to the World Health Organization, about 60 percent of blood donations collected globally each year is from voluntary unpaid blood donors. According to @list2011market, charitable gifts of money are worth two percent of gross domestic product for the United States. @lacetera2014rewarding stresses that: "27% of Americans volunteer with formal organizations, for a total of about 8 billion hours per year." A sizable scientific evidence on this topic comes from a series of studies based on economic games in the laboratory [see @levitt2007laboratory for a review] and in the field [@bandiera2005social; @dellavigna2016estimating]. @bandiera2005social, for instance, shows that workers internalize preferences of co-workers and may reduce effort under relative incentives. Likewise, @dellavigna2016estimating shows a positive effect of mission-oriented preferences, also called "vertical social preferences,"^[Social preferences towards peers are instead called "horizontal."] on the level of effort of freelance workers folding envelopes for a charity. Our work is consistent with a positive effect of vertical social preferences; adding evidence that such social preferences not only increase effort in mandatory pre-specified tasks but also affect voluntary participation to non-mandatory ones.^[In @dellavigna2016estimating, workers can choose how much effort to exert but cannot choose which task to work on (in this sense the task is "mandatory").]

Another important aspect of the present study is that we focus on incentives to carry out a complex task (writing a project proposal) as opposed to standardized production tasks [@knoeber1994testing] or sport [@ehrenberg1990tournaments]. We also focus on a competition  among individual workers instead of teams [e.g., @erev1993constructive, @hamilton2003team and more recently @gibbs2014field]. This allows us to remove from consideration important team dynamics such as peer pressure, monitoring, reciprocity among team members that may also affect the participation and effort quality of employees.  

<!-- In this attempt, @gibbs2014field is perhaps the study most closely related to ours. In an ideation task within a consulting firm, @gibbs2014field finds higher participation rates and quality with standard incentives tied to performance compared to flat wages. In that setting, however, employees are not competing for prizes and managers seek ideas that would "directly benefit the client, as compared to ideas that improve internal processes." Hence, an employee's idea is successful only when it is adopted by the client and has no direct impact on the organization. Our study is complementary to @gibbs2014field as we consider a competition (instead of standard pay-for-performance incentives) directed at improving the organization and its "internal processes." So, workers have an incentive to free ride not present in @gibbs2014field.^[Also, @gibbs2014field studies teams instead of individual workers. This implies that also in @gibbs2014field there may be a problem of free-riding within teams. Yet, formal teams are believed to solve internally the free-riding problem through peer pressure, monitoring, reciprocity within the team, etc. @hamilton2003team finds poor empirical evidence of free-riding in teams. In this sense, by focusing on individual workers, our results center on the problem of free-riding isolated from team dynamics.]  Overall, personal rewards have a positive effect on the participation but we find no (negative) quality effects. We argue this could result from the competition stopping workers from submitting innovation projects below a certain level of quality. -->

Finally, our work provides support to the incentive effect of a personal satisfaction derived from helping the organization achieving its goals [@akerlof2005identity; @besley2005competition; @delfgaauw2005dedicated; @delfgaauw2008incentives;  @prendergast2007motivation]. This type of altruism is believed to be an important driver of effort for workers in organizations for social public goods, such as hospitals, universities, schools, administrations, and the military. Theoretical models suggest different ways in which managers can exploit these prosocial motivations to raise individual productivity;  in the current study, we use framing to make particular motivations salient. We find that emphasizing prosocial motivations has countervailing effects on participation; negative for men and positive for women.^[Concerning framing, many studies have  explored the effects of positive or negative framing on the private provision of public goods in the laboratory [@andreoni1995warm]. Inside organizations, @hossain2012behavioralist and @hong2015framing are among the first studies to measure the impact of framing interventions on productivity. The current study adds to this literature by showing significant effects associated with a particular type of framing such as appealing to internal motivations towards the mission of the organization.] While this finding is consistent with altruism being one important driver of effort inside organizations, it also suggests that people are sensitive to framing and in ways that may be difficult to predict ex-ante.

<!-- 
The rest of the paper is organized as follows. The next section presents a simple analytical framework that we employ for estimating social preferences with the results of the field experiment. Section \ref{experimental-design} introduces the context and the experimental design. The data obtained from the experiment are presented in Section \ref{data}. Section \ref{results} presents the main empirical results.  Section \ref{discussion} gives an interpretation of the findings and a discussion of the main assumptions and concludes the paper.
 -->

Analytical framework and predictions
===================================

In this section, we conceptualize an internal solicitation for innovation project proposals to improve the operations of the organization as a voluntary contribution mechanism for a public good. Successful proposals are viewed as non-excludable because innovation leads to improvements for everyone in the workplace (including customers by increasing the quality and efficiency of the services provided). Submitting a proposal requires costly effort by employees, such as the time to identify a problem, form a proposal, write up a concise description, and the potential for further involvement during  proposal implementation.

Consider a linear model of the utility of a typical employee who contributes $x$ and benefits from total contributions of $Y=\sum x$:

\begin{equation} \label{eq:utility}
  u(R,~ Y) =  \gamma Y + \delta x + \frac{x}{Y} R - c x.
\end{equation}

The benefits of contributing derive from three sources. First, there is an altruistic benefit from the improved workplace, $\gamma Y$. The altruistic benefits are the crux of public goods. Only the existence of an improved workplace is desired and the source of contributions is irrelevant. Thus, everyone would prefer to free ride on others' efforts. Second, participants have some chance of winning the contest and can expect to derive benefits from the prizes, $\frac{x}{Y} R$, where, for simplicity, all efforts have an equal chance of being selected as the winner, as in @morgan2000financing. The personal reward $R$ can be thought of as a pecuniary prize, but it could also be an increase in prestige or recognition or any combination of the above.  Finally, employees may have an egoistic motivation for contributing "per se," regardless of winning and the effect on others, which is captured by $\delta x$. This includes the case in which workers may derive a personal satisfaction from contributing personally to the organization, often called warm glow preferences for giving [@andreoni1995warm]. Since we cannot observe the distinction between altruistic and warm-glow motives in our empirical setup, we are going to impose later that these preferences are such that $\delta=0$. 
 
Contributors incur some cost from developing and submitting a proposal, $c x$.  If there are $n$ employees the public goods dilemma arises when $\gamma+\delta < c < n\gamma+\delta$. Then no individual would contribute without a reward as costs exceed individual benefits, but everyone would be better off if everyone contributes. 

Suppose contributing a proposal is a discrete choice by employees. An employee can either contribute a single proposal $x=1$ and receive utility of 

\begin{equation}
	u_1 = \gamma \hat Y + \delta + \sum_{k=1}^{n}\Pr(Y=k)\frac{R}{k}  - c, 
\end{equation}

where $\hat Y$ denotes the expected level of contributions and $\Pr(Y=k)$ is the probability of having $k$ total contributions. Or they can contribute nothing $x=0$ and receive utility of 

\begin{equation}
  u_0 = \gamma (\hat Y - 1).
\end{equation}

If there are $n$ employees, then the unique symmetric mixed-strategy equilibrium is for each employee to contribute a proposal with probability $p>0$.  After using the binomial probability for $\Pr(Y=k)$, the payoff-equating condition to find a mixed-strategy equilibrium is:

\begin{equation} \label{eq: mixed-strategy}
  \frac{1- (1-p)^{n}}{n p} = (c- \gamma - \delta) / R.
\end{equation}

This equation admits one single solution $p^*$ which cannot be expressed explicitly. Using a first order Taylor expansion around $p$,  the equilibrium probability can be approximated as follows:

\begin{equation} \label{eq: probability}
  p^*  \approx \frac{2 (R- c+\gamma +\delta )}{(n-1) R}. 
\end{equation}

The analysis of the above model is used to derive the following predictions. 

1) The probability of contributing a proposal to improving the organization is zero when the prize for winning is sufficiently small relative to the individual cost of effort minus the preference for the public good (i.e., $R< c-\gamma +\delta$).

2) The probability of contributing a proposal to improve the organization increases with the value of the prize for winning.

3) The probability of contributing a proposal to improve the organization increases with the extent of individual preference for the public good ($\gamma+\delta$). 

Now suppose that the public good $Y$ constitutes the sum of innovation projects to improve the organization. Imagine that the quality of each project is randomly drawn from a discrete distribution, the same for every contributor (every employee who contributes is assumed to be equally likely to come up with a useful idea). Each proposal can be of high quality with probability $\nu$ and of low quality with probability $1-\nu$. If a proposal is of low quality, then the value for the organization is normalized to zero. The quality of proposals is learned only after the agent paid the cost of effort. Now the equilibrium public good $Y$ is not deterministic but follows a binomial distribution with average $E[Y] = p^{**} \nu n$, where the equilibrium probability $p^{**}$ can be derived as before with the only difference being that it is also an increasing function of the probability $\nu$. This leads to the following prediction. 

4) If the public good depends on the quality of each contribution and every agent is equally likely to make a proposal of high quality, then the higher the probability of contributing, the higher is the average public good.

This framework can be extended to the case of individuals with heterogeneous costs.  In the appendix, we explicitly consider the case of two types of individuals with different marginal costs of effort that form two groups of equal size. The symmetric mixed-strategy equilibrium is then characterized by the vector of probabilities of contributing with a proposal  $(p_1^\star, p_2^\star)$.  Here, the analysis of the payoff-equating conditions for the mixed-strategy equilibrium shows that the higher the marginal cost of effort minus preference for contributing, the lower the equilibrium probability of individuals (i.e., $p_1^\star > p_2^\star$ when $c_1 < c_2$, and vice versa).  This leads the final prediction. 

5) If individuals have heterogeneous costs, then the probability of contributing a proposal to improve the organization is higher for agents with lower costs (positive sorting).

