---
title: "Online Appendix: Incentives for Public Goods Inside Organizations: Field Experimental Evidence [NOT FOR PUBLICATION]"

thanks: "Blasco: Harvard Institute for Quantitative Social Science, Harvard University, 1737 Cambridge Street, Cambridge, MA 02138 (email: ablasco@fas.harvard.edu). Jung: Harvard Business School, Soldiers Field, Boston, MA 02163 (email: ojung@hbs.edu), Lakhani: Harvard Business School, Soldiers Field, Boston, MA 02163, and National Bureau of Economic Research (email: k@hbs.edu). Menietti: Harvard Institute for Quantitative Social Science, Harvard University, 1737 Cambridge Street, Cambridge, MA 02138 (email: mmenietti@fas.harvard.edu). We gratefully acknowledge the financial support of the MacArthur Foundation (Opening Governance Network), NASA Tournament Lab, and the Harvard Business School Division of Faculty Research and Development.  This project would not have been possible without the support of Eric Isselbacher, Julia Jackson, Maulik Majmudar and Perry Band from the Massachusetts General Hospital's Healthcare Transformation Lab."

abstract: "In this online appendix, we present a formal proof of the result of sorting in the extended model with heterogenous costs, as discussed in the main paper. We report additional tables and results to support the analysis discussed in the main text. We also  provide copy of the solicitation sent, the graphics used for the headings of the website, and the text of the 'rules of the competition' page of the contest's website."

date: "Last updated: `r format(Sys.time(), '%d %B, %Y')`"

author: 
    - Andrea Blasco
    - Olivia S. Jung
    - Karim R. Lakhani
    - Michael Menietti
---

```{r, echo=FALSE, warnings=FALSE, message=FALSE}
knitr::opts_chunk$set(
  cache=FALSE,
  echo=FALSE,
  message=FALSE,
  warning=TRUE,
  error=FALSE,
  tidy=FALSE,
  fig.width=5,
  fig.height=5,
  cache.path="Cache/",
  fig.path="Figures/")

source("config.Rmd")
```

```{r child = '5_appendix.Rmd'}
```