---
title: "Contributing to Public Goods Inside Organizations: Field Experimental Evidence"

thanks: "Blasco: Harvard Institute for Quantitative Social Science, Harvard University, 1737 Cambridge Street, Cambridge, MA 02138 (email: ablasco@fas.harvard.edu). Jung: Harvard Business School, Soldiers Field, Boston, MA 02163 (email: ojung@hbs.edu), Lakhani: Harvard Business School, Soldiers Field, Boston, MA 02163, and National Bureau of Economic Research (email: k@hbs.edu). Menietti: Harvard Institute for Quantitative Social Science, Harvard University, 1737 Cambridge Street, Cambridge, MA 02138 (email: mmenietti@fas.harvard.edu). We gratefully acknowledge the financial support of the MacArthur Foundation (Opening Governance Network), NASA Tournament Lab, and the Harvard Business School Division of Faculty Research and Development.  This project would not have been possible without the support of Eric Isselbacher, Julia Jackson, Maulik Majmudar and Perry Band from the Massachusetts General Hospital's Healthcare Transformation Lab."

date: "Last updated: `r format(Sys.time(), '%d %B, %Y')`"

author: 
    - Andrea Blasco
    - Olivia S. Jung
    - Karim R. Lakhani
    - Michael Menietti

abstract: "Employees often make choices between working on their assignment and on privately observed opportunities to improve the organization. Inefficient decisions may arise due to an incentive to free-riding on the work of others. An internal competition for prizes may help workers make more efficient choices but it may be detrimental to motivated workers. Using a solicitation of innovation project proposals in a medical center with over 1200 employees, we find that a contest awarding pecuniary prizes for the best contributions generates an 85 percent increase in participation, with no effects on the quality of contributions. The participation effect is the same for men and women, staff with different roles, and appears beyond the value of the prize. We also find that a solicitation appealing to improving the workplace is effective. But emphasizing the patient mission of the organization led to countervailing effects on participation based on gender differences. These results indicate that awarding prizes is a powerful way to foster contributions to organizational public goods, suggesting a complementarity between incentives and underlying motivations associated with the mission of the organization."

JEL: 
  - H41
  - D23
  - D03

keywords: 
  - innovation contest
  - free rider problem
  - social preferences
  - altruism
  - idea generation
  - organization of work

endfloat: false

---

```{r, echo=FALSE, warnings=FALSE, message=FALSE}
knitr::opts_chunk$set(
  cache=FALSE,
  echo=FALSE,
  message=FALSE,
  warning=TRUE,
  error=FALSE,
  tidy=FALSE,
  fig.width=5,
  fig.height=5,
  cache.path="Cache/",
  fig.path="Figures/")

source("config.Rmd")
```

```{r child = '1_intro.Rmd'}
```

```{r child = '2_methods.Rmd'}
```

```{r child = '3_results.Rmd'}
```

```{r child = '4_discussion.Rmd'}
```


References
=============
