# Introduction

Employees divide their time between production tasks and organizational tasks---solving common problems, innovating. Both activities generate costs for the employee and benefits for the organization. One key distinction is that work in production tasks benefits, for the most part, the employer (and indirectly the worker through performance pay or promotion), whereas organizational work is aimed to enhance the organization as a whole, generating thus positive externalities to the other employees as well.[^examples]

[^examples]: There are many examples of employee-driven contributions that have improved their workplace, increased productivity,  make the company more  "green," etc. 

These externalities complicate the analysis of incentives inside organizations. One general problem is that employees may view work made by their peers as a substitute for their own work, and may be tempted to "free ride" instead. This situation may thus lead to inefficient employee decisions resulting in a low participation and little improvement efforts for the organization.

One popular way to remedy the incentives is to launch an organization-wide competition---a contest---to foster the provision of the public good, such as encouraging work in organizational improvement opportunities. It is, however, still unclear what makes contests particularly appealing solutions. Based  on the literature, we hypothesize three main reasons:  (1) the chance of winning an individual prize gives employees an additional incentive to contribute to the public good [@morgan2000financing]; (2) the contest draws the attention of employees to relevant organizational needs, thus leveraging employees' underlying motivations towards the organizational goals;[^mission-oriented] and (3) the  contests allocates additional resources (e.g., implementation money) to the winners, thus increasing the value of  each single employee contribution.

[^examples]: EXAMPLES HERE 

[^mission-oriented]: @besley2005competition calls these underlying motivations _mission-oriented preferences._ "Workers are typically motivated agents, i.e., agents who pursue goals because they perceive intrinsic benefits of doing so. There are many examples --- doctors who are committed to saving lives, researchers to advancing knowledge, judges to promoting justice, and soldiers to defending their country in battle."

[^caveat]: As shown by @morgan2000financing, this property holds only when (i) the chances of winning are proportional to one's contribution to the public good and (ii) the value of the prize is fixed (independent of effort).

<!-- 
All these strategies have strengths and weaknesses that have been studied in the theoretical literature. Making contributions compulsory can be inefficient unless the employer has full information (about employees' skills and preferences). Voluntary contribution mechanisms should be preferred to mandatory contributions when these can leverage the "altruistic" preferences of their employees (e.g., attachment to the mission of the organization, feelings towards the co-workers). And a competition for prizes could yield greater contributions than voluntary mechanisms [@morgan2000financing]. But only when (i) the chances of winning are proportional to oneÕs contribution and (ii) the value of the prize is fixed (independent of effort). [Sorting] and [Crowding-out] <!--  These requirements, however, are hard to meet exactly, especially when the contribution is improvement work inside an organization (instead of giving money). 
-->

In this study, we investigate the relative effectiveness of these incentives to gain a better understanding of how organization-wide contests can encourage higher levels of employee contributions to the organizational public good. We use a _natural field experiment_ to compare the responses of staff members of a medical organization who are exposed to four different "solicitation" treatments (i.e., contest announcements soliciting organizational improvement opportunities): (1) a solicitation treatment (PRIZE) that highlights the opportunity of winning a prize for the best contribution, (2) a solicitation treatment (WPLACE) that replaces the information about the prize opportunity by general encouragements towards improving the workplace, or (3) improving the care of patients (PCARE), and (4) a solicitation treatment (FUND) that, instead of a prize or general encouragement, highlights the opportunity of obtaining implementation money to turn the best contributions into action.

The empirical context for the experiment is the Massachusetts General Hospital's (MGH) Corrigan Minehan Heart Center (simply referred to as the "Heart Center") a prominent medical organization in the United States and a teaching hospital of the Harvard Medical School. The health care delivery context is particularly relevant as the need for organizational improvement and innovation is vastly noted [@cutler2012reducing]. In addition, health care professionals are commonly seen as willing to step beyond the boundaries of their contractual duties to offer better care [@delfgaauw2005dedicated], which makes the comparison of different incentives towards a public good especially relevant and interesting.  

The subject pool was the entire population of the Heart Center consisting of over 1,200 staff members including physicians, nurses, and administrative staff.  The intervention was associated with an internal contest aimed to improve the operations of the organization, in the spirit of "open innovation" discussed in @terwiesch2008innovation, @lakhani2013prize, and @glaeser2016predictive. The contest solicited employees to submit project proposals describing an existing problem and providing a solution to address the problem. After the submission phase, the contest invited all employees to read and rate each proposal on a five-point scale. The winning proposal would receive funding for implementation, implying additional costs and responsibilities from making a winning proposal (e.g., providing further guidance or a direct involvement in implementation). 

Our solicitation treatments were randomly assigned to each staff member, thus allowing us to obtain causal estimates of the effect of different solicitation strategies on two main outcomes: (a) the decision to submit a proposal and engage in an organizational improvement task and (b) the quality of the submissions as measured by over 12,000 peer ratings and by the management (the contest organizers). We further check the effects on employee participation of differences in preferences or other characteristics associated with the employee's profession, gender, and position inside the organization.

<!-- Results -->
We find that the PRIZE solicitation treatment boosts participation by about 40 percent relative to the WPLACE and PCARE general encouragements. The FUND solicitation treatment, by contrast, not only generates about three times less submissions than the PRIZE solicitation treatment but also generates less submissions than the WPLACE and PCARE solicitation treatments with general encouragements. Taken together, these findings suggest that (1) the competition-for-prizes incentive dominates mission-oriented incentives and (2) the opportunity of additional resources to lead implementation of one's own submitted idea, a non-production task, is perceived more as a penalty than a reward.

We also find that these participation differences are without lowering the quality of the submissions (as judged by peers or the management).[^agreement] The higher employee participation in the PRIZE solicitation treatment does not seem to be driven by low-quality submissions. Similarly, the lower employee participation in the FUND solicitation treatment does not seem to be driven by high-quality submissions. Overall, these findings suggest no trade-off between quantity and quality; treatments that attracted more participation resulted in proposals of comparable quality and content. 

[^agreement]: We find good agreement (sufficiently positive correlation) in the assessed quality of proposals between peer ratings and the evaluations conducted by the management; thus suggesting incentives being sufficiently aligned.

<!-- 
Sorting. Interactions. The size of the effect is about the same for men and women and for staff members employed in different professions (and, therefore, differing in income, education, etc.). There is sorting but xxxx higher up in the organization. 
 -->

Participation in the WPLACE and PCARE solicitation treatments is equally effective on average. However, these solicitations around the mission of the organization resulted in responses that appear sensitive to the gender of the solicited person. Women's participation is greater when emphasizing the patient care whereas men's participation is significantly lower, controlling for the profession and position inside the organization. This finding suggests that gender may influence sensitivity to framing concerning the organizational mission. 

At the same time, we find insignificant gender-based differences with respect to participation in the PRIZE treatment: women's participation was slightly higher but not significant than men's, all else being equal. This evidence indicates that gender differences in preferences, such as competitive inclinations or risk aversion, may not exert great influence on responses of workers to contests inside organizations. 
 
<!-- Literature -->

# Literature

The present study contributes to the literature on the use of contests in the workplace. From a principal-agent perspective, contests are often viewed as compensation mechanisms that exhibit good properties when the cost of monitoring effort is too high to permit conventional contractual solutions [@lazear1981rank; @green1983comparison; @mary1984economic]. Conventional theory, however, presumes that the employer enjoy the work of the competitors _exclusively_ (e.g., sales, revenues), and there are no positive externalities for the contestants. We expand this perspective by considering contests used to increase the employee provision of the public good inside organizations. And we focus on three main drivers of participation: (1) the opportunity of winning a prize; (2) a call to action that triggers underlying motivations towards contributing; and (3) the opportunity of winning implementation money.

Our empirical results are complementary to the existing empirical literature on contests. There are indeed numerous studies that have examined contests in a wide range of empirical contexts ---firms, sports, the laboratory, and online platforms [@bull1987tournaments; @eriksson1999executive; @ehrenberg1990tournaments; @terwiesch2008innovation; @terwiesch2009innovation; @boudreau2011incentives; @boudreau2016performance]. We depart from these studies by focusing on a complex task (writing a project proposal) as opposed to standardized production tasks. This focus allows us to study the trade-off between incentivizing quantity (of participants) and quality (of submissions), which xxxxx. 


We also focus on a competition  among individual workers instead of teams [e.g., @erev1993constructive, @hamilton2003team and more recently @gibbs2014field]. This allows us to remove from consideration important team dynamics such as peer pressure, monitoring, reciprocity among team members that may also affect the participation and effort quality of employees.  


<!-- 
Despite this extensive literature, we examine a situation that has received relatively less attention in the past. Namely, how contests can be used to increase the provision of the public good inside organizations. We consider three main drivers: (1) the opportunity of winning a prize; (2) a call to action that triggers underlying motivations towards contributing; and (3) the opportunity of winning implementation money. 
Another difference with existing empirical studies on contests is that 
 -->

Our work also contributes to the empirical literature on how to finance public goods. We follow the perspective of @morgan2000financing that xxxxx.  A number of works have shown a positive effect of prizes on the extent of individual contributions to a public good in the laboratory [@morgan2000funding; @dale2004charitable; @lange2007using] and in the field [@landry2006toward]. However, as noted by @vesterlund2012voluntary, the existing evidence on the profitability of contest-type mechanisms for raising money for public goods (e.g., charity donations) is only mixed. Our work provides further evidence to this theory as we extend the results of past studies to an organizational setting. Within this setting, individual contributions are non-monetary but consist of time and effort in putting forward (and implementing) a proposal, and the public good consists of the potential improvements for the organization. Under such circumstances, we find evidence indicating that offering prizes can effectively raise the level of participation (compared to voluntary mechanisms) and overall appear to be a profitable solution for organizations.

Our results also relate to the literature on social preferences at work. A number of studies have shown that people tend to contribute to public goods despite strong incentives to free ride. According to the World Health Organization, about 60 percent of blood donations collected globally each year is from voluntary unpaid blood donors. According to @list2011market, charitable gifts of money are worth two percent of gross domestic product for the United States. @lacetera2014rewarding stresses that: "27% of Americans volunteer with formal organizations, for a total of about 8 billion hours per year." A sizable scientific evidence on this topic comes from a series of studies based on economic games in the laboratory [see @levitt2007laboratory for a review] and in the field [@bandiera2005social; @dellavigna2016estimating]. @bandiera2005social, for instance, shows that workers internalize preferences of co-workers and may reduce effort under relative incentives. Likewise, @dellavigna2016estimating shows a positive effect of mission-oriented preferences, also called "vertical social preferences,"^[Social preferences towards peers are instead called "horizontal."] on the level of effort of free-lance workers folding envelopes for a charity. Our work is consistent with a positive effect of vertical social preferences; adding evidence that such social preferences not only increase effort in mandatory pre-specified tasks but also affect voluntary participation to non-mandatory ones.^[In @dellavigna2016estimating, workers can choose how much effort to exert but cannot choose which task to work on (in this sense the task is "mandatory").]


<!-- In this attempt, @gibbs2014field is perhaps the study most closely related to ours. In an ideation task within a consulting firm, @gibbs2014field finds higher participation rates and quality with standard incentives tied to performance compared to flat wages. In that setting, however, employees are not competing for prizes and managers seek ideas that would "directly benefit the client, as compared to ideas that improve internal processes." Hence, an employee's idea is successful only when it is adopted by the client and has no direct impact on the organization. Our study is complementary to @gibbs2014field as we consider a competition (instead of standard pay-for-performance incentives) directed at improving the organization and its "internal processes." So, workers have an incentive to free ride not present in @gibbs2014field.^[Also, @gibbs2014field studies teams instead of individual workers. This implies that also in @gibbs2014field there may be a problem of free-riding within teams. Yet, formal teams are believed to solve internally the free-riding problem through peer pressure, monitoring, reciprocity within the team, etc. @hamilton2003team finds poor empirical evidence of free-riding in teams. In this sense, by focusing on individual workers, our results center on the problem of free-riding isolated from team dynamics.]  Overall, personal rewards have a positive effect on the participation but we find no (negative) quality effects. We argue this could result from the competition stopping workers from submitting innovation projects below a certain level of quality. -->

Finally, our work provides support to the incentive effect of a personal satisfaction derived from helping the organization achieving its goals [@akerlof2005identity; @besley2005competition; @delfgaauw2005dedicated; @delfgaauw2008incentives;  @prendergast2007motivation]. This type of altruism is believed to be an important driver of effort for workers in organizations for social public goods, such as hospitals, universities, schools, administrations, and the military. Theoretical models suggest different ways in which managers can exploit these pro-social motivations to raise individual productivity;  in the current study, we use framing to make particular motivations salient. We find that emphasizing pro-social motivations has countervailing effects on participation; negative for men and positive for women.^[Concerning framing, many studies have  explored the effects of positive or negative framing on the private provision of public goods in the laboratory [@andreoni1995warm]. Inside organizations, @hossain2012behavioralist and @hong2015framing are among the first studies to measure the impact of framing interventions on productivity. The current study adds to this literature by showing significant effects associated with a particular type of framing such as appealing to internal motivations towards the mission of the organization.] While this finding is consistent with altruism being one important driver of effort inside organizations, it also suggests that people are sensitive to framing and in ways that may be difficult to predict ex-ante.

<!-- 
The rest of the paper is organized as follows. The next section presents a simple analytical framework that we employ for estimating social preferences with the results of the field experiment. Section \ref{experimental-design} introduces the context and the experimental design. The data obtained from the experiment are presented in Section \ref{data}. Section \ref{results} presents the main empirical results.  Section \ref{discussion} gives an interpretation of the findings and a discussion of the main assumptions and concludes the paper.
 -->

# Analytical framework and predictions

In this section, we conceptualize an internal solicitation for innovation project proposals to improve the operations of the organization as a voluntary contribution mechanism for a public good. Successful proposals are viewed as non-excludable because innovation leads to improvements for everyone in the workplace (including customers by increasing the quality and efficiency of the services provided). Submitting a proposal requires costly effort by employees, such as the time to identify a problem, form a proposal, write up a concise description, and the potential for further involvement during  proposal implementation.

Consider a linear model of the utility of a typical employee who contributes $x$ and benefits from total contributions of $Y=\sum x$:

\begin{equation} \label{eq:utility}
  u(R,~ Y) =  \gamma Y + \delta x + \frac{x}{Y} R - c x.
\end{equation}

The benefits of contributing derive from three sources. First, there is an altruistic benefit from the improved workplace, $\gamma Y$. The altruistic benefits are the crux of public goods. Only the existence of an improved workplace is desired and the source of contributions is irrelevant. Thus, everyone would prefer to free ride on others' efforts. Second, participants have some chance of winning the contest and can expect to derive benefits from the prizes, $\frac{x}{Y} R$, where, for simplicity, all efforts have an equal chance of being selected as the winner, as in @morgan2000financing. The personal reward $R$ can be thought of as a pecuniary prize, but it could also be an increase in prestige or recognition or any combination of the above.  Finally, employees may have an egoistic motivation for contributing "per se," regardless of winning and the effect on others, which is captured by $\delta x$. This includes the case in which workers may derive a personal satisfaction from contributing personally to the organization, often called warm glow preferences for giving [@andreoni1995warm]. Since we cannot observe the distinction between altruistic and warm-glow motives in our empirical setup, we are going to impose later that these preferences are such that $\delta=0$. 
 
Contributors incur some cost from developing and submitting a proposal, $c x$.  If there are $n$ employees the public goods dilemma arises when $\gamma+\delta < c < n\gamma+\delta$. Then no individual would contribute without a reward as costs exceed individual benefits, but everyone would be better off if everyone contributes. 

Suppose contributing a proposal is a discrete choice by employees. An employee can either contribute a single proposal $x=1$ and receive utility of 

\begin{equation}
	u_1 = \gamma \hat Y + \delta + \sum_{k=1}^{n}\Pr(Y=k)\frac{R}{k}  - c, 
\end{equation}

where $\hat Y$ denotes the expected level of contributions and $\Pr(Y=k)$ is the probability of having $k$ total contributions. Or they can contribute nothing $x=0$ and receive utility of 

\begin{equation}
  u_0 = \gamma (\hat Y - 1).
\end{equation}

If there are $n$ employees, then the unique symmetric mixed-strategy equilibrium is for each employee to contribute a proposal with probability $p>0$.  After using the binomial probability for $\Pr(Y=k)$, the payoff-equating condition to find a mixed-strategy equilibrium is:

\begin{equation} \label{eq: mixed-strategy}
  \frac{1- (1-p)^{n}}{n p} = (c- \gamma - \delta) / R.
\end{equation}

This equation admits one single solution $p^*$ which cannot be expressed explicitly. Using a first order Taylor expansion around $p$,  the equilibrium probability can be approximated as follows:

\begin{equation} \label{eq: probability}
  p^*  \approx \frac{2 (R- c+\gamma +\delta )}{(n-1) R}. 
\end{equation}

The analysis of the above model is used to derive the following predictions. 

1) The probability of contributing a proposal to improving the organization is zero when the prize for winning is sufficiently small relative to the individual cost of effort minus the preference for the public good (i.e., $R< c-\gamma +\delta$).

2) The probability of contributing a proposal to improve the organization increases with the value of the prize for winning.

3) The probability of contributing a proposal to improve the organization increases with the extent of individual preference for the public good ($\gamma+\delta$). 

Now suppose that the public good $Y$ constitutes the sum of innovation projects to improve the organization. Imagine that the quality of each project is randomly drawn from a discrete distribution, the same for every contributor (every employee who contributes is assumed to be equally likely to come up with a useful idea). Each proposal can be of high quality with probability $\nu$ and of low quality with probability $1-\nu$. If a proposal is of low quality, then the value for the organization is normalized to zero. The quality of proposals is learned only after the agent paid the cost of effort. Now the equilibrium public good $Y$ is not deterministic but follows a binomial distribution with average $E[Y] = p^{**} \nu n$, where the equilibrium probability $p^{**}$ can be derived as before with the only difference being that it is also an increasing function of the probability $\nu$. This leads to the following prediction. 

4) If the public good depends on the quality of each contribution and every agent is equally likely to make a proposal of high quality, then the higher the probability of contributing, the higher is the average public good.

This framework can be extended to the case of individuals with heterogeneous costs.  In the appendix, we explicitly consider the case of two types of individuals with different marginal costs of effort that form two groups of equal size. The symmetric mixed-strategy equilibrium is then characterized by the vector of probabilities of contributing with a proposal  $(p_1^\star, p_2^\star)$.  Here, the analysis of the payoff-equating conditions for the mixed-strategy equilibrium shows that the higher the marginal cost of effort minus preference for contributing, the lower the equilibrium probability of individuals (i.e., $p_1^\star > p_2^\star$ when $c_1 < c_2$, and vice versa).  This leads the final prediction. 

5) If individuals have heterogeneous costs, then the probability of contributing a proposal to improve the organization is higher for agents with lower costs (positive sorting).

