# Introduction

Understanding what motivates employees to go above and beyond an effective execution of their own assigned tasks is a key question for many organizations. Much empirical work, however, has mainly looked at the problem from an *agency* perspective in which employees are expected to work above the levels enforceable by contracts with benefits that are enjoyed mainly the employer, such as increased sale revenues. Less attention has been paid to situations where employees are expected to make contributions that create benefits for everyone in the workplace (including customers by increasing the quality and efficiency of the services provided), such as those towards improving the operations of the organization.

[^INCOMPLETE]: It is indeed impossible for firms to provide for all possible contingencies via role specification and contractual incentives [@alchian1972production], and a firm's ability to increase the willingness of employees to make voluntary contributions is an asset of difficult imitation by competitors.

In such situations, a free rider problem can be xxx and may result in inefficient decisions with respect to the workplace innovation. Consider, for example, the case of a worker contemplating several ideas to improve the workplace. The worker knows it takes time to turn these different ideas into concrete proposals and the effort devoted to this task, being outside normal job duties, will receive little, or no, direct compensation along with an uncertain recognition from the management. But the worker also knows that a successful innovation will carry benefits for its own work, for that of colleagues, and for clients. What will the worker do? According to the classical theoretical view, it will ignore the effects on the rest of the organization and act only when personal benefits exceed costs of turning ideas into actions. Against this view, alternative theories have assumed that employees are moved by *altruistic* motivations towards specific individuals or groups inside the organization [@rotemberg2006altruism], or a desire to help the organization achieve its "mission" [@akerlof2005identity; @besley2005competition] --- as it appears to be for workers employed by organizations providing public services like hospitals, schools, and the public administration [@delfgaauw2005dedicated; @delfgaauw2008incentives; @prendergast2007motivation]. Ultimately, the question is an empirical one: how effective these alternative motivations are? and how to design a work environment that fosters employees' contributions to internal public goods?

In this study, we conduct a natural field experiment to address these questions and provide evidence on the effectiveness of personal rewards and mission-oriented incentives. The experiment was carried out at a medical organization with more than 1200 employees (doctors, nurses, administrative workers). The opportunity for the experiment was an organization-wide solicitation seeking employee participation in an internal innovation contest. The contest was offering employees -- at all levels of the organization -- the opportunity of submitting innovation project proposals to improve the operations of the organization. Submitting a proposal required costly effort by employees, such as the time to identify a problem, form a proposal, write up a concise description, and the potential for further involvement during  proposal implementation; but it was also an opportunity for helping coworkers and helping the organization (including providing better health care to the patients).

By manipulating the content of personalized solicitation emails sent out to all staff members (doctors, nurses, and administrative workers) at the beginning of the innovation contest, the experiment tested incentives for contributing  such as offering (*i*) small personal awards for winning submissions, (*ii*) funding for implementation of own projects; and it tested the use of content appealing directly to employees' altruistic motivations towards (*iii*) improving patient care (a mission-oriented incentive) or (*iv*) helping the co-workers via suggestions to improve the workplace.

The healthcare delivery context of the experiment is important for two main reasons. First, the need for organizational improvement and innovation is vastly noted [@cutler2012reducing]. Second, health care professionals are commonly seen as willing to step beyond the boundaries of their contractual duties to offer better care [@delfgaauw2005dedicated], which makes the comparison of different incentives towards a public good especially relevant and interesting.

The focus on employee participation in an innovation contest is for both practical and theoretical considerations. First, the launch of an internal contest offers a very convenient setting for experimental interventions to study how employees self-select themselves into new tasks without affecting the normal operations of the firm. Most organizations have indeed adopted centralized information systems that make relatively easy to run organization-wide contests.[^EXAMPLES] And, as a byproduct of these systems, it is inexpensive for researchers to intervene by altering some features of the contest itself -- or the communication around the contest -- in a way to separately identify channels associated with extrinsic and intrinsic reasons for participating, such as, for instance, using a personalized messaging strategy that conveys information about the presence of personal awards for the winners, or omits that information.

Another reason to focus on an empirical setting that includes an internal innovation contest is theoretical. In the context of public goods games, @morgan2000financing has shown that a simple contest, where competitors raise their probability of winning a fixed prize by making greater contributions to the public good, can increase the equilibrium provision. The intuition behind this result is that the contribution an agent makes will inevitably reduce the chances of others winning the same prize, thus creating a negative externality. @morgan2000financing shows that, since the agents will ignore the positive and negative effects of their contributions to others, the presence of a negative externality associated with the prize competition counteracts the underprovision associated with the positive externality of contributing to a public good. This result has received much attention [@vesterlund2012voluntary], as it provides an economic rationale for the use of prizes in a variety of contexts such as charity donations. However, it may not extend to employees inside organizations where, among many other reasons, agents share social connections and may internalize the losses on their co-workers [as in @bandiera2005social]. So, one of the aims of this study is to test whether prizes help to foster the internal provision of public goods. 

<!-- 
Much of the existing literature in economics points to choosing to perform discretionary tasks with little, or no, formal recognition as a rational way to obtain extrinsic benefits, such as career advancements or a good reputation.[^CAREERS] But this kind of behavior has been also linked to a form of *altruism* that goes from the worker to the other members of the organization [@bandiera2005social; @rotemberg2006altruism] or from the worker to  its clients, such as that of doctors towards their patients [@delfgaauw2005dedicated] or civil servants towards citizens [@delfgaauw2008incentives; @prendergast2007motivation] for whom altruistic feelings can be  inspired by the "mission" of the organization [@akerlof2005identity; @besley2005competition]. However, the lack of systematic empirical evidence on employee behavior makes difficult to assess the strength of these different motivations, thus giving a poor indication of what motivates workers when they decide to help the organization.[^LABORATORY]

[^CAREERS]: Since career advancements are uncertain and depend on a variety of conditions and not on productivity alone, the prospect of a promotion provide motivations to do extra-work [@kreps1997intrinsic]. @gibbons1999careers gives a survey of the theoretical literature on careers in organizations.

[^LABORATORY]: There is a large literature that has looked at these preferences in the laboratory in settings that mimic the employee-employer relationship [see XXX for example].

In this study, we conduct a natural field experiment to provide evidence on the effectiveness of personal rewards and mission-oriented incentives within an internal innovation contest at a medical organization. The internal innovation contest aimed to spur voluntary contributions (project proposals) to organizational improvement from its more than 1200 employees. The experiment tested incentives for contributing by manipulating the content of personalized emails soliciting staff participation, such as offering ($i$) awards for winning submissions, ($ii$) funding for implementation of own projects, and appealing to intrinsic motivations towards ($iii$) improving patient care (a mission-oriented incentive) or ($iv$) the workplace.

one primary goal is to examine how employees respond to a public good dilemma in a field setting where both extrinsic and intrinsic motives are likely to be present. In particular, we examine empirically how over 1,200 staff members (doctors, nurses, and administrative staff) of an elite medical organization in the United States respond to an organization-wide call to submit proposals for improving the organization to an *internal innovation contest*. Such innovation contest solicited employees to submit project proposals describing an existing problem and providing a solution to address the problem, in the spirit of "open innovation" contests discussed in @terwiesch2008innovation; @lakhani2013prize; and @glaeser2016predictive. The entire staff was then invited to read and rate each proposal on a five-point scale. Based on these ratings and other criteria, the winning proposal would receive funding for implementation, implying additional costs and responsibilities from making a winning proposal (e.g., providing further guidance or a direct involvement in implementation).
 -->

Within this experimental setting, we evaluate the causal impact of our four randomly assigned experimental conditions on two main response variables: (a) employee participation measured by the decision to submit a proposal and engage in an organizational improvement task and (b) the quality of the submissions as measured by (over 12,000) peer ratings and by assessments of the management.

Testing the presence of both participation and quality effects is important as the presence of systematic quality differences associated with different motivations would substantially complicate the problem of incentives for the organization (a higher employee participation is a less desirable goal if it is driven by  low-quality proposals). We also investigate the presence of sorting effects based on the gender, profession, and position inside the organization of the solicited employee, and whether there are  heterogenous treatment effects associated with these characteristics. For example, following the literature on gender-based differences in preferences [@croson2004gender], the gender may impact the willingness to participate in a contest for prizes, complicating the analysis of the incentives. 

<!-- Results -->
Our key results are the following. First, a solicitation offering the opportunity of winning a prize dominates all other incentives, leading to a sizable and significant increase in employee participation rates. Such an increase in participation, we find, is without lowering the quality of the submissions; and we provide evidence that it goes beyond the extrinsic value of the prize, consistently with Morgan's theory of prizes as means to foster provision of public goods.  By contrast, the solicitation offering grant money to lead the implementation of one's own submitted project proposal is the least effective incentive, leading to a lower employee participation rate relative to all the other treatments and with no difference in quality. The size of these effects is nontrivial. Had all the staff members been offered prize incentives, the organization would have received three times the submissions had they all been offered the funding incentives; and the received proposals would have had the same quality on average. 

Second, by looking at the sorting patterns by gender, profession, and position inside the organization, we find that mission-oriented incentives result in responses that appear sensitive to the gender of the solicited person. In particular,  women's response to solicitations for improving patient care is higher than men's. We also find that women's and men's response to solicitations for prizes are the same; thus suggesting that gender differences in preferences, such as competitive inclinations or risk aversion, may not exert great influence on responses of workers to the competition-for-prizes incentive.

These results seem to suggest that workers better internalize the positive effect of their contributions and participate more in collective tasks when they are offered a personal award, even if the value of the prize is small relative to the costs of contributing. This result is important because it highlights a relatively less understood function of contests that is to mitigate the free riding incentives on organizational tasks.  A second implication is that offering the opportunity to lead collective projects can exacerbate the free riding incentives. This result is important because projects need to be lead by someone and making resources available does not seem to increase volunteers. A third implication is that participation in organizational tasks is sometimes triggered by mission-based preferences, but these preferences may also create gender-based selection effects that are difficult to predict ex-ante and we point to the extensive literature on gender-based difference in preferences [see @croson2009gender for a review] or difference in self-stereotypes [@coffman2014evidence] to explain some of these effects.

This paper contributes to the literature using within-firm field experiments to understand employee motivations, as surveyed by @bandiera2011field. In particular, it contributes to the literature on the effects of social incentives on the workplace [@bandiera2005social; bandiera2008social; @bandiera2010social; @dellavigna2016estimating] by providing evidence that supports the presence of altruistic preferences affecting the willingness of workers to sort into discretionary tasks with collective benefits. It also contributes to the literature investigating how prize-based competitions provide motivations at work [@knoeber1994testing; @ehrenberg1990tournaments; @blanes2011tournaments; @boudreau2011incentives; @barankay2012rank;  @delfgaauw2013tournament; @ashraf2014awards; @gibbs2014field; @boudreau2016performance]; although it differs from existing studies in that it focuses on (1) a collective task potentially yielding benefits to everyone on the workplace (including the opponents); and (2) a complex task, such as submitting project proposals, with a possible quantity and quality trade-off. This paper is also broadly related to the empirical literature on the free rider problem in team production [@erev1993constructive; @hamilton2003team; @boning2007opportunity; @mas2009peers; @gibbs2014field]; although it differs from much of the existing literature in that it focuses on a situation where peer effects are muted, such as peer pressure, monitoring, reciprocity among team members, and other kinds of social interactions that are usually seen as opposing to free riding.  Finally, this paper is also related to a recent field experimental literature on mission-oriented incentives [@carpenter2016motivating] potentially connecting this literature with that on gender-based differences in preferences [@croson2009gender].

<!-- 
# Literature

This paper adds to the existing empirical literature on within-firm field experiments [covered in the survey by @bandiera2011field].  but it differs from previous studies in this literature, such as xxxx, as it focuses on In this sense, our study is also related to the empirical literature on social preferences on the workplace [@bandiera2005social] and mission-oriented preferences [@dellavigna2016estimating; xxxxx]. Our findings suggest that emphasizing mission-oriented motivations has countervailing effects: positive for women and negative for men. While this finding is consistent with altruism being an important driver of effort inside organization, it also suggests that people are sensitive to the framing and in ways that may be difficult to predict ex-ante.
It is related to xxx in what situations awards effectively motivate individuals, such as Ashraf xxxx, 

Our study is also related to the extensive literature on prize-based incentives at work. Economists have long recognized that prize-based competitions are an important  source of incentives inside organizations [@lazear1981rank; @green1983comparison; @nalebuff1983prizes; @mary1984economic]. Much of the existing theoretical literature in labor economics, however, presumes that agents are motivated to compete solely on the basis of the utility derived by winning one of the prizes. Less attention has been devoted to situations in which a competitor's performance generates public good effects for the other competitors, and the whole organization; a notable exception is XXX. By focusing on incentives to workers to do organizational tasks (tasks with public good effects for the organization), we improve the existing literature in this direction. for which there exist consistent findings across many different empirical settings, including sport competitions [@ehrenberg1990tournaments], production competitions in firms [@knoeber1994testing; @terwiesch2008innovation], and more recently online competitions [@boudreau2011incentives; @boudreau2016performance]. 

The paper is also related to studies on free riding incentives in the context of team production [@erev1993constructive; @hamilton2003team; @boning2007opportunity;  @gibbs2014field]; although it differs from much of the existing literature  in that it focuses on a situation where conventional group incentives are muted, such as peer pressure, monitoring, reciprocity among team members, and other kinds of social interactions that have been shown to affect behavior in the presence of free riding incentives.

Finally, we borrow from the literature in public economics that studies prize-based mechanisms to foster the provision of public goods. @morgan2000funding appears to be the first to note that fixed-prize lotteries -- a special case also known as "Tullock" contest -- are widely used tools among non-profit fund raising firms, showing conditions under which these may increase the provision relative to voluntary contributions. This insight has spurred much attention in public economics with several studies testing this idea empirically [see @vesterlund2012voluntary for a survey]. However, as noted by Vesterlund, the existing evidence on the profitability of lotteries for charities is only mixed. Our work extends the existing literature on the topic by focusing on an organizational setting where monetary contributions are replaced by effort and the "greater good" is helping the organization achieve its goals. Within this context, we find evidence that fixed-prize contests are a profitable tool to foster public good effects inside firms. 
 -->

# Conceptual framework and predictions

In this section, we conceptualize an internal solicitation for innovation project proposals to improve the operations of the organization as a voluntary contribution mechanism for a public good. Successful proposals are viewed as non-excludable because innovation leads to improvements for everyone in the workplace (including customers by increasing the quality and efficiency of the services provided). Submitting a proposal requires costly effort by employees, such as the time to identify a problem, form a proposal, write up a concise description, and the potential for further involvement during  proposal implementation.

Consider the public good $Y$ constitutes the sum of innovation projects to improve the organization.[^SUMMATION] Imagine that the quality of each project is randomly drawn from a discrete distribution, the same for every contributor (every employee who contributes is assumed to be equally likely to come up with a useful idea). Each proposal can be of high quality with probability $\nu$ and of low quality with probability $1-\nu$. If a proposal is of low quality, then the value for the organization is normalized to zero. The quality of proposals is learned only after the agent paid the cost of effort. 

[^SUMMATION]: Instead of using a summation, we could have used different functional forms for the collective benefits (e.g., the max). However, the presence of free-riding incentives does not crucially depend on this specific assumption.

Let consider first the simplest case where the probability $\nu=1$ so any project is of high quality for sure. We assume a linear model of the utility of a typical employee who contributes $x$ and benefits from total contributions of $Y=\sum x$:

\begin{equation}\label{eq:utility}
  u(R,~ Y) =  \gamma Y + \delta x + \frac{x}{Y} R - c x.
\end{equation}

The benefits of contributing derive from three sources. First, there is an altruistic benefit from the improved workplace, $\gamma Y$. The altruistic benefits are the crux of public goods. Only the existence of an improved workplace is desired and the source of contributions is irrelevant. Thus, everyone would prefer to free ride on others' efforts. Second, participants have some chance of winning the contest and can expect to derive benefits from the prizes, $\frac{x}{Y} R$, where, for simplicity, all efforts have an equal chance of being selected as the winner, as in @morgan2000financing. The personal reward $R$ can be thought of as a pecuniary prize, but it could also be an increase in prestige or recognition or any combination of the above.  Finally, employees may have an egotistic motivation for contributing "per se," regardless of winning and the effect on others, which is captured by $\delta x$. This includes the case in which workers may derive a personal satisfaction from contributing personally to the organization, often called warm glow preferences for giving [@andreoni1995warm]. Since we cannot observe the distinction between altruistic and warm-glow motives in our empirical setup, we are going to impose later that these preferences are such that $\delta=0$. 
 
Contributors incur some cost from developing and submitting a proposal, $c x$.  If there are $n$ employees the public goods dilemma arises when $\gamma+\delta < c < n\gamma+\delta$. Then no individual would contribute without a reward as costs exceed individual benefits, but everyone would be better off if everyone contributes. 

Suppose contributing a proposal is a discrete choice by employees. An employee can either contribute a single proposal $x=1$ and receive utility of 

\begin{equation}
	u_1 = \gamma \hat Y + \delta + \sum_{k=1}^{n}\Pr(Y=k)\frac{R}{k}  - c, 
\end{equation}

where $\hat Y$ denotes the expected level of contributions and $\Pr(Y=k)$ is the probability of having $k$ total contributions. Or they can contribute nothing $x=0$ and receive utility of 

\begin{equation}
  u_0 = \gamma (\hat Y - 1).
\end{equation}

If there are $n$ employees, then the unique symmetric mixed-strategy equilibrium is for each employee to contribute a proposal with probability $p>0$.  After using the binomial probability for $\Pr(Y=k)$, the payoff-equating condition to find a mixed-strategy equilibrium is:

\begin{equation} \label{eq: mixed-strategy}
  \frac{1- (1-p)^{n}}{n p} = (c- \gamma - \delta) / R.
\end{equation}

This equation admits one single solution $p^*$ which cannot be expressed explicitly. Using a first order Taylor expansion around $p$,  the equilibrium probability can be approximated as follows:

\begin{equation} \label{eq: probability}
  p^*  \approx \frac{2 (R- c+\gamma +\delta )}{(n-1) R}. 
\end{equation}

The analysis of the above model is used to derive the following predictions. 

1) The probability of contributing a proposal to improving the organization is zero when the prize for winning is sufficiently small relative to the individual cost of effort minus the preference for the public good (i.e., $R< c-\gamma +\delta$).

2) The probability of contributing a proposal to improve the organization increases with the value of the prize for winning.

3) The probability of contributing a proposal to improve the organization increases with the extent of individual preference for the public good ($\gamma+\delta$). 

Now suppose that the probability $\nu$ is less than one. The equilibrium public good $Y$ is not deterministic but follows a binomial distribution with average $E[Y] = p^{**}\nu n$, where the equilibrium probability $p^{**}$ can be derived as before with the only difference being that it is also an increasing function of the probability $\nu$. This leads to the following prediction. 

4) If the public good depends on the quality of each contribution and every agent is equally likely to make a proposal of high quality, then the higher the probability of contributing, the higher is the average public good.

This framework can be extended to the case of individuals with heterogeneous costs.  In the appendix, we explicitly consider the case of two types of individuals with different marginal costs of effort that form two groups of equal size. The symmetric mixed-strategy equilibrium is then characterized by the vector of probabilities of contributing with a proposal  $(p_1^\star, p_2^\star)$.  Here, the analysis of the payoff-equating conditions for the mixed-strategy equilibrium shows that the higher the marginal cost of effort minus preference for contributing, the lower the equilibrium probability of individuals (i.e., $p_1^\star > p_2^\star$ when $c_1 < c_2$, and vice versa).  This leads the final prediction. 

5) If individuals have heterogeneous costs, then the probability of contributing a proposal to improve the organization is higher for agents with lower costs (positive sorting).



<!-- FOOTNOTES -->

[^PROFESSORS]: Professors, for example, are expected to teach and publish research (with pay and tenure tied to performance in those tasks) and also to serve on various internal committees that directly benefit the university and department operations, with indirect benefit to committee members. Similarly, in companies, employees are expected to work on production activities and also to contribute to common resources, collaborate in teams, provide feedback on strategy and direction of the firm, and drive innovation efforts. 

[^EXAMPLES]: Among the many examples of internal contests that have appeared in the news are the Apple's 2016 contest among its store employees seeking ideas on how to improve the way it sells iPhones ("Apple seeks 'pie in the sky' ideas for innovation," Computerworld, 2013); Xerox's internal contest seeking employees ideas on how to make a more environmentally friendly workplace environment ("Xerox employees green ideas save company $10.2 million," The Guardian, 2010); and AT&T's ideation contests seeking employee ideas about new products ("AT&T develops employee ideas for innovation," The Wall Street Journal, 2014).

[apple]: http://www.computerworld.com/article/2474058/smartphones/apple-seeks--pie-in-the-sky--ideas-for-innovation
[Xerox]:  http://www.theguardian.com/sustainable-business/xerox-employees-green-ideas-save
[at&t]: http://blogs.wsj.com/cio/2014/11/12/att-develops-employee-ideas-for-innovation

