
# Introduction

<!--
"Organizational Citizen Behavior; the good soldier syndrome" (Book, xxxx) defines this type of behavior as "discretionary, not directly recognized by the formal reward system, and that promotes the effective functioning of the organization." 

@ashraf2014no studies efforts in HIV prevention finds that non-financial rewards are effective at improving performance.  
-->

The effective functioning of organizations -- both in business and non-profit -- crucially depends on the willingness' of their members to volunteer time and effort in tasks that go beyond their regular duties and produce generalized benefits. Typical examples are attending decisional committees, suggesting improvements in workplace practices, and experimenting with new ideas. Despite the relevance for the organization, managers often struggle to identify employees and use formal incentives to have them perform these tasks. 

In many cases, organizations use internal contests -- organization-wide competitions -- to foster employee participation and self-selection into these tasks. These internal contests may affect behavior through many mechanisms: (1) financial awards; (2) empowering workers to run their own projects; and (3) triggering workers' pro-social preferences.

In this paper, we report the results of a *natural field experiment* to unbundle the xxxx. That is, we try to assess the relative effectiveness of these three alternative incentives in the field. 

In particular, the experiment involved more than 1200 staff members of a medical organization (doctors, nurses, and administrative staff) in the United States. St

 we compare the responses of the entire staff member who were xxxx four different *solicitation treatments.* These are email contest announcements seeking participation in an organization-wide internal contest about project proposals for organizational improvement. All the four solicitation emails were identical except for the first paragraph which was assigned at random to isolate different motives: (1) the opportunity of winning an individual reward (PRIZE); (2) the opportunity of winning implementation money to lead one's own improvement project (FUND); (3) a generic call to improve the workplace (WPLACE) with no direct individual reward for the winners; and (4) a generic call to improve the care of patients (PCARE) with no direct individual reward for the winners. 



In this paper we study xxxx. 
An internal contest may remedy the incentives by providing a formal recognition to the workers who sorted xxx and achieved the xxxx. The design of the awards and the overall intent of the competition may largely affect participation of the different members of the organization, revealing workers' actual reasons for contributing to the organization. Based on this insight, we conduct a natural field experiment to assess the relative importance of xxx, xxx, and xxx. 


The choice of sorting on these tasks yields an immediate cost for the worker but also benefits for specific individuals, or groups, within the organization or the organization as a whole. This means that non-altruistic workers may be tempted to behave opportunistically and free ride, hoping that others will sort on these tasks. But, at the same time, workers may feel compelled to go the extra mile at work for organizations pursuing *social public goods* (hospitals, schools, and non-profits) because of the intrinsic satisfaction from contributing to the organization for its own good.


 
An internal contest may remedy the incentives by providing a formal recognition to top contributors. The design of the awards and the overall intent of the competition may largely affect participation of the different members of the organization, revealing workers' actual reasons for contributing to the organization. Based on this insight, we conduct a natural field experiment to assess the relative importance of xxx, xxx, and xxx. 


A first mechanism is the incentive effect of winning a personal reward. Theory predicts that, even in the context of public good provision, prize-based competitions are better than voluntary mechanisms. In particular, as shown by xxx, non-altruistic agents will contribute beyond the value of the awarded prize when (i) the chances of winning are proportional to one's effort and (ii) the value of the prize is fixed (independent of effort). This is because the internal contest may generate two opposing externalities: a negative externality from trying to win the personal reward over the other employees; and a positive externality from contributing effort to the public good. Organizations can hence use small awards to get more than xxx participation rates and higher returns per dollar. 

However, prizes can also generate negative sorting effects. Low-quality ideas, which is a waste. Crowding-out which is even worst. 


A second potential mechanism is to use contests to award internal resources to xxxx. In this case, employees may be more willing to participate as they xxxx. There might be psychological benefits from "being in charge". But also private aspects of the public good could appropriate xxxx.  have no budget constrain. In addition, when the implementation of a public good can still be more or less favorable for certain groups within the organization, the opportunity to influence xxxx of internal resources to projects that are useful to them (for the next years) can be a stronger incentive than just winning a small personal reward.  ... (2) the competition awards implementation resources to the best projects, thus giving workers the opportunity of influencing the allocation of collective resources towards preferred interventions (e.g., obtaining implementation money for own projects).  

A third potential mechanism is to appeal to xxxx.  an internal contest is also an opportunity for the management to mark specific organizational needs to the workers. This request may then trigger voluntary contributions from workers out of their underlying motivations towards helping the organization achieve its goals xxxx [@besley2005competition; @rotemberg2006altruism].  Intrinsic incentives may be "altruism" directed at specific individuals or groups within the organization (horizontal social preferences) or at the organization as a whole (vertical social preferences). There exist studies in psychology that have used surveys to measure xxxx. Overall they say that: preferences correlate weakly.  ... may be affected by a number of factors both *tangible* such as costs of required effort and *intangible* like social preferences on the workplace (xxxx). For example, workers employed by organizations with a "mission" like those pursuing xxxx (hospitals, schools, and non-profits) may have a relatively higher propensity to do xxxx than other workers, as they might feel an "intrinsic satisfaction" from helping the organization achieve its goals. But it is also possible that workers may have an incentive to free ride on one another, despite the xxxx. More generally, it can be difficult for organizations to motivate workers effectively since little is known about what drives workers' decisions to work on tasks that are like public goods inside organizations.




Workers employed by firms are often expected to perform *organizational tasks*  -- i.e., activities that go beyond their regular duties and produce generalized benefits for the organization -- like volunteer time in committees, indicate improvements for workplace practices, innovate.^[EXAMPLE OF PROFESSORS]  For the management's perspective, it is central to engage the workforce in these tasks because different workers are often in a better position to identify areas that need improvements and find the solutions; although it might be difficult to do so with formal incentives (xxxx). But also from the employees' perspective, being engaged in organizational tasks is advantageous to xxxx direction of the firm and contribute and xxx promote change xxxx, although, of course, it can also be costly, especially when it subtracts time to their formal duties. This concomitance of generalized benefits and individual costs may create a public good dilemma; workers may be tempted to free-ride, hoping that other members of the organization will pay the cost of the required effort; and may need to be encouraged through some kind of incentive scheme. 


In this paper, we focus on internal contests -- organization-wide  competitions for prizes [xxxx] -- as a way to address this problem and raise the levels of participation and engagement of employees in tasks that produce public good effects for the entire organization. In other words, we investigate the ways in which an internal competition that seek contributions to common goods can remedy the free-riding incentives when workers face a public good dilemma.

The focus on internal contests is in part justified by the growing popularity of contests as a source of incentives inside firms. Among the many examples that have appeared in the news are the Apple's 2016 contest among its over xxx store employees seeking ideas on how to improve the way it sells iPhones; Xerox's 20XX  internal contest seeking employees ideas on how to make a more environmentally friendly workplace environment; IBM's 20xxx contests on employee ideas to improve xxxx internal communication; and AT&T's xxx contests seeking employee ideas about new products [xxxx].[^sources] And one may well expect this trend to intensify as organizations do more xxxx and workers can xxxx.

[^sources]: See: "Apple seeks 'pie in the sky' ideas for innovation," [Computerworld][apple]; "Xerox employees green ideas save company $10.2 million," [The Guardian][xerox]; XXXXX, and "AT&T develops employee ideas for innovation," [The Wall Street Journal][at&t]). 

[apple]: http://www.computerworld.com/article/2474058/smartphones/apple-seeks--pie-in-the-sky--ideas-for-innovation
[Xerox]:  http://www.theguardian.com/sustainable-business/xerox-employees-green-ideas-save
[at&t]: http://blogs.wsj.com/cio/2014/11/12/att-develops-employee-ideas-for-innovation


Another motivation to focus on internal contests in a public good context is to complement the existing economic literature on contests. There exists indeed a large literature in economics on the use of contests inside firms [@lazear1981rank; @green1983comparison; @nalebuff1983prizes; and @mary1984economic; xxxxx]. Yet, the existing literature has been mainly focused on tasks that have no public good effects. Here we do xxxx. Despite its popularity, it is still unclear the mechanism through internal contests.  xxxx. Specifically, we hypothesize and test empirically three main mechanisms by which an internal contest can remedy the incentives in this case.
 
First, the incentive effect of competition is higher when there are public good xxxx. As shown by @morgan2000financing, non-altruistic agents engaged in a competition that seeks contributions to public goods and awards personal rewards to the winners (i.e., the best contributors) will contribute beyond the value of the awarded prize when (i) the chances of winning are proportional to one's effort and (ii) the value of the prize is fixed (independent of effort). This is because the internal contest may generate two opposing externalities: a negative externality from trying to win the personal reward over the other employees; and a positive externality from contributing effort to the public good. Therefore, even small personal rewards relative to the cost of contributing will mitigate the free-riding incentive.  

This contrasts with the view of xxxx where the contest fail because of the pg. 

A second potential incentive is to award resources fxxxx. In this case, employees may be more willing to participate as they xxxx. There might be psychological benefits from "being in charge". But also private aspects of the public good could appropriate xxxx.  have no budget constrain. In addition, when the implementation of a public good can still be more or less favorable for certain groups within the organization, the opportunity to influence xxxx of internal resources to projects that are useful to them (for the next years) can be a stronger incentive than just winning a small personal reward.  ... (2) the competition awards implementation resources to the best projects, thus giving workers the opportunity of influencing the allocation of collective resources towards preferred interventions (e.g., obtaining implementation money for own projects).  

A third potential mechanism is xxxxx.  an internal contest is also an opportunity for the management to mark specific organizational needs to the workers. This request may then trigger voluntary contributions from workers out of their underlying motivations towards helping the organization achieve its goals xxxx [@besley2005competition; @rotemberg2006altruism].  Intrinsic incentives may be "altruism" directed at specific individuals or groups within the organization (horizontal social preferences) or at the organization as a whole (vertical social preferences). There exist studies in psychology that have used surveys to measure xxxx. Overall they say that: preferences correlate weakly.  ... may be affected by a number of factors both *tangible* such as costs of required effort and *intangible* like social preferences on the workplace (xxxx). For example, workers employed by organizations with a "mission" like those pursuing xxxx (hospitals, schools, and non-profits) may have a relatively higher propensity to do xxxx than other workers, as they might feel an "intrinsic satisfaction" from helping the organization achieve its goals. But it is also possible that workers may have an incentive to free ride on one another, despite the xxxx. More generally, it can be difficult for organizations to motivate workers effectively since little is known about what drives workers' decisions to work on tasks that are like public goods inside organizations.

We empirically assess the relative effectiveness of these three alternative incentives in the field. Using a _natural field experiment_ among the staff members of a medical organization, we compare the responses of the entire staff member who were xxxx four different *solicitation treatments.* These are email contest announcements seeking participation in an organization-wide internal contest about project proposals for organizational improvement. All the four solicitation emails were identical except for the first paragraph which was assigned at random to isolate different motives: (1) the opportunity of winning an individual reward (PRIZE); (2) the opportunity of winning implementation money to lead one's own improvement project (FUND); (3) a generic call to improve the workplace (WPLACE) with no direct individual reward for the winners; and (4) a generic call to improve the care of patients (PCARE) with no direct individual reward for the winners. 

The empirical context for the experiment is the Massachusetts General Hospital's (MGH) Corrigan Minehan Heart Center (simply referred to as the "Heart Center") a prominent medical organization in the United States and a teaching hospital of the Harvard Medical School. The health care delivery context is particularly relevant as the need for organizational improvement and innovation is vastly noted [@cutler2012reducing]. In addition, health care professionals are commonly seen as willing to step beyond the boundaries of their contractual duties to offer better care [@delfgaauw2005dedicated], which makes the comparison of different incentives towards a public good especially relevant and interesting.  

The subject pool was the entire population of the Heart Center consisting of over 1,200 staff members including physicians, nurses, and administrative staff.  The intervention was associated with an internal contest aimed to improve the operations of the organization, in the spirit of "open innovation" discussed in @terwiesch2008innovation, @lakhani2013prize, and @glaeser2016predictive. The contest solicited employees to submit project proposals describing an existing problem and providing a solution to address the problem. After the submission phase, the contest invited all employees to read and rate each proposal on a five-point scale. The winning proposal would receive funding for implementation, implying additional costs and responsibilities from making a winning proposal (e.g., providing further guidance or a direct involvement in implementation). 

Within this empirical context, our solicitation treatments were randomly assigned to each staff member, thus allowing us to obtain causal estimates of the effect of different solicitation strategies on two main outcomes: (a) employee participation measured by the decision to submit a proposal and engage in an organizational improvement task and (b) the quality of the submissions as measured by (over 12,000) peer ratings and by the management organizing the contest. 

Testing the presence of both participation and quality effects is important as it would substantially complicate the problem of incentives for the organization. Quality effects can arise when, for example, the allure of winning a prize may attract to the competition workers with low-quality proposals, who wouldn't have participated otherwise. At the same time, the presence of compensation can discourage intrinsically motivated agents who might xxxx; thus lowering quality of xxxx. More generally, sorting is xxxx. So, we further check the effects on employee participation of differences in preferences or other characteristics associated with the employee's profession, gender, and position inside the organization. The presence of sorting effects based on the gender, for example, may impact on the extent and type of public goods provided, complicating the analysis of the incentives substantially. 


[^mission]:  According to @besley2005competition, "Workers are typically motivated agents, i.e., agents who pursue goals because they perceive intrinsic benefits of doing so. There are many examples -- doctors who are committed to saving lives, researchers to advancing knowledge, judges to promoting justice, and soldiers to defending their country in battle."

[^caveat]: As shown by @morgan2000financing, this property holds only when (i) the chances of winning are proportional to one's contribution to the public good and (ii) the value of the prize is fixed (independent of effort).


<!---
In this study, we investigate empirically the relative effectiveness of these incentives to better understand how organization-wide contests can foster contributions to public goods inside organizations. We use a _natural field experiment_ to compare the responses of staff members of a medical organization who are exposed to four different "solicitation" treatments -- contest announcements -- seeking projects for organizational improvement. These are: (1) a solicitation treatment (PRIZE) announcing the opportunity of winning a prize for the best proposals; (2) a solicitation treatment (WPLACE) announcing a generic opportunity of improving the workplace; (3) a solicitation treatment (PCARE)  announcing a generic opportunity of improving the care of patients; and (4) a solicitation treatment (FUND) announcing the opportunity of obtaining implementation money to lead one's own improvement project.
-->

<!-- Results -->

As we shall discuss in Section \ref{results}, results indicate that our solicitation treatments produce significant effects on employee participation in the contest, with small and insignificant effects on the quality of the proposals. In particular, our findings suggest that: (1) the opportunity of winning a prize dominates all other incentives; (2) the opportunity of leading implementation of one's own submitted project proposal, a non-production task, is the least effective incentive and seems to be perceived more as a cost than a reward; (3) the increase in participation rates associated with the announcement of a prize is without lowering the quality of submissions; and using a simple linear public-good model, we estimate that (4) responses to the prize incentive may go beyond the extrinsic value of the prize, consistently with our theory of prizes as means to internalize public goods. 

In addition, by looking at the sorting by gender, profession, and position inside the organization, we find that: (5) solicitation treatments with mission-oriented incentives may result in responses that appear sensitive to the gender of the solicited person (women's response to solicitations for improving patient care is higher than men's); and (6) gender differences in preferences, such as competitive inclinations or risk aversion, may not exert great influence on responses of workers to the competition-for-prizes incentive (women's and men's response to solicitations for prizes are the same). 

The implications of these results for the provision of public goods inside organizations are discussed in Section \ref{summary-and-conclusions}. 

<!-- Literature -->

# Literature

Economists have long recognized that prize-based competitions are an important  source of incentives inside organizations [@lazear1981rank; @green1983comparison; @nalebuff1983prizes; @mary1984economic]. Much of the existing theoretical literature in labor economics, however, presumes that agents are motivated to compete solely on the basis of the utility derived by winning one of the prizes. Less attention has been devoted to situations in which a competitor's performance generates public good effects for the other competitors, and the whole organization; a notable exception is XXX. By focusing on incentives to workers to do organizational tasks (tasks with public good effects for the organization), we improve the existing literature in this direction. 

 for which there exist consistent findings across many different empirical settings, including sport competitions [@ehrenberg1990tournaments], production competitions in firms [@knoeber1994testing; @terwiesch2008innovation], and more recently online competitions [@boudreau2011incentives; @boudreau2016performance]. 

To be sure, free riding incentives inside organizations have been widely studied in labor economics, especially in the context of team production [@erev1993constructive; @hamilton2003team; @boning2007opportunity;  @gibbs2014field]. However, our study differs from much of the existing literature  in that it focuses on an individual competition where the team component is missing. That is,  the public good dilemma comes from externalities towards anyone in the organization, not just a set of identified team members. It follows that one can remove from consideration conventional team dynamics such as peer pressure, monitoring, reciprocity among team members, and other kinds of social interactions that have been shown to affect behavior in the presence of free riding incentives.

Our study is also related the literature in public economics that studies prize-based mechanisms to foster the provision of public goods. @morgan2000funding appears to be the first to note that fixed-prize lotteries -- a special case also known as "Tullock" contest -- are widely used tools among non-profit fundraising firms, showing conditions under which these may increase the provision relative to voluntary contributions. This insight has spurred much attention in public economics with several studies testing this idea empirically [see @vesterlund2012voluntary for a survey]. However, as noted by Vesterlund, the existing evidence on the profitability of lotteries for charities is only mixed. Our work extends the existing literature on the topic by focusing on an organizational setting where monetary contributions are replaced by effort and the "greater good" is helping the organization achieve its goals. Within this context, we find evidence that fixed-prize contests are a profitable tool to foster public good effects inside firms. 


Finally, our work provides support to the incentive effect of mission-oriented preferences -- inner satisfaction from helping the organization achieve its goals -- [@akerlof2005identity; @besley2005competition; @delfgaauw2005dedicated; @delfgaauw2008incentives;  @prendergast2007motivation; @rotemberg2006altruism] and social preferences at work [@bandiera2005social; @bandiera2008social; @bandiera2013team; @dellavigna2016estimating]. According to this perspective,  workers are motivated agents. They do their work because they care about their co-workers, employers, and customers. Theoretical models suggest different ways in which managers can exploit these intrinsic motivations to raise individual levels of participation and productivity. Here, we use announcing an internal contest for organizational improvements to make these motivations salient. We find that emphasizing mission-oriented motivations has countervailing effects: positive for women and negative for men. While this finding is consistent with altruism being an important driver of effort inside organization, it also suggests that people are sensitive to the framing and in ways that may be difficult to predict ex-ante.

# Analytical framework and predictions

In this section, we conceptualize an internal solicitation for innovation project proposals to improve the operations of the organization as a voluntary contribution mechanism for a public good. Successful proposals are viewed as non-excludable because innovation leads to improvements for everyone in the workplace (including customers by increasing the quality and efficiency of the services provided). Submitting a proposal requires costly effort by employees, such as the time to identify a problem, form a proposal, write up a concise description, and the potential for further involvement during  proposal implementation.

Consider a linear model of the utility of a typical employee who contributes $x$ and benefits from total contributions of $Y=\sum x$:^[functionalform]

[^functionalform]: This assumption is realistic if one consider that the quality of the submissions is a random variable that is realized only after the submission process, as we shall discuss later. We could have used different functional forms for the collective benefits (e.g., the max). Yet, the problem of free-riding incentives does not depend on this specific assumption.

\begin{equation} \label{eq:utility}
  u(R,~ Y) =  \gamma Y + \delta x + \frac{x}{Y} R - c x.
\end{equation}

The benefits of contributing derive from three sources. First, there is an altruistic benefit from the improved workplace, $\gamma Y$. The altruistic benefits are the crux of public goods. Only the existence of an improved workplace is desired and the source of contributions is irrelevant. Thus, everyone would prefer to free ride on others' efforts. Second, participants have some chance of winning the contest and can expect to derive benefits from the prizes, $\frac{x}{Y} R$, where, for simplicity, all efforts have an equal chance of being selected as the winner, as in @morgan2000financing. The personal reward $R$ can be thought of as a pecuniary prize, but it could also be an increase in prestige or recognition or any combination of the above.  Finally, employees may have an egoistic motivation for contributing "per se," regardless of winning and the effect on others, which is captured by $\delta x$. This includes the case in which workers may derive a personal satisfaction from contributing personally to the organization, often called warm glow preferences for giving [@andreoni1995warm]. Since we cannot observe the distinction between altruistic and warm-glow motives in our empirical setup, we are going to impose later that these preferences are such that $\delta=0$. 
 
Contributors incur some cost from developing and submitting a proposal, $c x$.  If there are $n$ employees the public goods dilemma arises when $\gamma+\delta < c < n\gamma+\delta$. Then no individual would contribute without a reward as costs exceed individual benefits, but everyone would be better off if everyone contributes. 

Suppose contributing a proposal is a discrete choice by employees. An employee can either contribute a single proposal $x=1$ and receive utility of 

\begin{equation}
	u_1 = \gamma \hat Y + \delta + \sum_{k=1}^{n}\Pr(Y=k)\frac{R}{k}  - c, 
\end{equation}

where $\hat Y$ denotes the expected level of contributions and $\Pr(Y=k)$ is the probability of having $k$ total contributions. Or they can contribute nothing $x=0$ and receive utility of 

\begin{equation}
  u_0 = \gamma (\hat Y - 1).
\end{equation}

If there are $n$ employees, then the unique symmetric mixed-strategy equilibrium is for each employee to contribute a proposal with probability $p>0$.  After using the binomial probability for $\Pr(Y=k)$, the payoff-equating condition to find a mixed-strategy equilibrium is:

\begin{equation} \label{eq: mixed-strategy}
  \frac{1- (1-p)^{n}}{n p} = (c- \gamma - \delta) / R.
\end{equation}

This equation admits one single solution $p^*$ which cannot be expressed explicitly. Using a first order Taylor expansion around $p$,  the equilibrium probability can be approximated as follows:

\begin{equation} \label{eq: probability}
  p^*  \approx \frac{2 (R- c+\gamma +\delta )}{(n-1) R}. 
\end{equation}

The analysis of the above model is used to derive the following predictions. 

1) The probability of contributing a proposal to improving the organization is zero when the prize for winning is sufficiently small relative to the individual cost of effort minus the preference for the public good (i.e., $R< c-\gamma +\delta$).

2) The probability of contributing a proposal to improve the organization increases with the value of the prize for winning.

3) The probability of contributing a proposal to improve the organization increases with the extent of individual preference for the public good ($\gamma+\delta$). 

Now suppose that the public good $Y$ constitutes the sum of innovation projects to improve the organization. Imagine that the quality of each project is randomly drawn from a discrete distribution, the same for every contributor (every employee who contributes is assumed to be equally likely to come up with a useful idea). Each proposal can be of high quality with probability $\nu$ and of low quality with probability $1-\nu$. If a proposal is of low quality, then the value for the organization is normalized to zero. The quality of proposals is learned only after the agent paid the cost of effort. Now the equilibrium public good $Y$ is not deterministic but follows a binomial distribution with average $E[Y] = p^{**} \nu n$, where the equilibrium probability $p^{**}$ can be derived as before with the only difference being that it is also an increasing function of the probability $\nu$. This leads to the following prediction. 

4) If the public good depends on the quality of each contribution and every agent is equally likely to make a proposal of high quality, then the higher the probability of contributing, the higher is the average public good.

This framework can be extended to the case of individuals with heterogeneous costs.  In the appendix, we explicitly consider the case of two types of individuals with different marginal costs of effort that form two groups of equal size. The symmetric mixed-strategy equilibrium is then characterized by the vector of probabilities of contributing with a proposal  $(p_1^\star, p_2^\star)$.  Here, the analysis of the payoff-equating conditions for the mixed-strategy equilibrium shows that the higher the marginal cost of effort minus preference for contributing, the lower the equilibrium probability of individuals (i.e., $p_1^\star > p_2^\star$ when $c_1 < c_2$, and vice versa).  This leads the final prediction. 

5) If individuals have heterogeneous costs, then the probability of contributing a proposal to improve the organization is higher for agents with lower costs (positive sorting).

