
# Summary and conclusions

We report results of a natural field experiment conducted at a medical organization that held an innovation contest seeking contribution of public goods (i.e., projects for organizational improvement) from its more than 1200 employees. The experiment tested incentives for contributing by manipulating the content of emails soliciting staff participation. We presented different incentives to participate in the contest, such as a prize (PRIZE) for winning submissions, improving patient care (PCARE), improving the workplace (WPLACE), and funding for implementation (FUND). Each staff was randomly assigned to receiving an email containing one of the four incentives. 

We find that the PRIZE solicitation treatment boosts participation by about 40 percent relative to the WPLACE and PCARE solicitation treatments. The FUND solicitation treatment is the least effective. It generates not only about three times less submissions than the PRIZE solicitation treatment, but also less submissions than the WPLACE and PCARE solicitation treatments. 

These participation differences, we find, are without changing the quality of the submissions as judged by peers and the management.[^agreement] The higher employee participation in the PRIZE solicitation treatment does not seem to be driven by low-quality submissions. Similarly, the lower employee participation in the FUND solicitation treatment does not seem to be driven by high-quality submissions. In other words, treatments that attracted more (or less) participation resulted in proposals of comparable quality and content.

[^agreement]: We find good agreement (high positive correlation) in the assessed quality of proposals between peer ratings and the evaluations conducted by the management; thus suggesting incentives being sufficiently aligned.

Taken together, these findings suggest that (1) the competition-for-prizes incentive dominates mission-oriented incentives and (2) the opportunity to lead implementation of one's own submitted project proposal is a poor incentive. In addition, these effects combined with the small (extrinsic) value of the prize relative to the median income of the participants, the long odds of winning the prize, the lack of differences in participation among professions, and the foreseeable additional costs of winning may suggest that (3) the effect of a prize competition on participation goes beyond the actual value of the prize itself, suggesting workers have, in fact, internalized some of the benefits of participating in an organizational task. 

We also fined that, although the WPLACE and PCARE solicitation treatments are equally effective on average, responses appear sensitive to the gender of the solicited person. Women's participation is greater when emphasizing the patient care whereas men's participation is significantly lower, controlling for the profession and position inside the organization. This finding suggests that gender may be an important factor influencing sensitivity of responses to solicitations concerning the organizational mission.

At the same time, only an insignificant gender-based differences with respect to participation in the PRIZE solicitation treatment was found: women's participation was slightly higher but not significant than men's, all else being equal. This evidence indicates that gender differences in preferences, such as competitive inclinations or risk aversion, may not exert great influence on responses of workers to contests inside organizations. 

We believe these results have three main implications for comparable organizations and, more broadly, the internal provision of public goods.

The first implication is that announcing a competition for an individual prize foster workers' participation in organizational tasks beyond the value of the awarded prize itself. That is, prizes generate two opposing externalities that help workers internalize the public good effects of their organizational contributions. This result is important because it highlights a relatively less understood function of contests that is to mitigate the free riding incentives on organizational tasks. 

A second implication is that offering the opportunity to lead collective projects can exacerbate the free riding incentives. This result may appear contrary to intuition. In theory, one may benefit more from leading a project than winning an iPad. For instance, one may use the opportunity to signal project management skills to the management aiming for a career advancement; or steer some of the resources towards assets or problems that are relatively more beneficial to his or her situation compared to the rest of the organization. If so, why a negative result? We believe that the private benefits from winning were negligible in our setting. First, the opportunity for a career advancement is small because medical staff gets promoted on the basis of other parameters (e.g., the quality of care provided). Second, the peer evaluation and vetting by the management ensure that the winning contributions yield as distributed benefits as possible. These aspects may have eliminated the possible private benefits from leading a project, resulting in poor participation rates. This result is important because projects need to be lead by someone and making more resources available does not seem to increase volunteers.


A third implication is that participation in organizational tasks is sometimes triggered by mission-based preferences. Although we find evidence that these preferences can be an effective incentive, we also find gender-based selection effects that are difficult to predict ex-ante. Our experiment does not provide any insights to better interpret these differences. But a large literature has investigated gender-based difference in preferences [see @croson2009gender for a review] or difference in self-stereotypes [@coffman2014evidence] that could explain some of these effects. Yet, more experimentation is needed to understand the different drivers in the field inside organizations. 

A few limitations of this study deserve consideration. The first is that the validity of our causal interpretation of the results rests on a few conventional assumptions [@rubin1974estimating]. These include the "no interference between units" assumption.  In our study, it is possible that communication among staff assigned to different treatment arms could have influenced decisions to participate. The magnitude of this interference would depend on intensity of staff communication and the density of social interactions. Both of which should be small because (i) an individual competition may provide only weak incentives for information sharing and (ii) the staff members are scattered across multiple buildings on the hospital campus. Even so, a potential inference bias may alter the results towards a null effect as differences in employee participation should converge towards zero when communication spreads the content of the different email solicitations. This goes against our results. Moreover, by looking at the temporal dynamics of submissions, we find no indication of a convergence in the participation rates. Hence, the assumption of no interference seems appropriate.

Another potential limitation is that staff members may have left the solicitation email that was sent to them unopened or unread, thus non-complying with the assigned solicitation treatment. As this kind of noncompliance is almost entirely unobserved,^[The email was sent using the internal messaging system of the Heart Center, which, at the time, was not collecting individual analytics.] the analysis follows an _Intention-To-Treat_ (ITT) approach, discarding entirely any information about the solicitation treatment actually received. The main drawback of an ITT analysis is that it does not answer questions about causal effects of the content of the solicitation itself, only about causal effects of the assignment to a solicitation treatment.


<!-- 
Another drawback lies in the complex nature of motivation xxxx in fields experiments within organizations, using their members as unit of analysis. Staff members are subjected to many different incentives like career incentives, reputation, etc. This complex situation may xxxx confound xxxx factors. 0. Possible confounding factors: career concerns, reputation, prizes, credibility, costs.
1. Another possible confounding factor is that xxx immediate rewards vs long-term rewards. Under this view, the prize effect is a combination of xxx This is not against our interpretation. 
2. Another issue is that the contest was at the first time. This might have impacted credibility. If so, people may have not believed the funding. However, the management ensured the legitimacy of the interventions xxx. Indeed, all three winning proposals got implemented. If so, a lack of credibility may have xxx. 
3. Another problem is the presence of non-monetary incentives other than contributing to common assets. Two in particular: (1) career advancement, (2) gain a public recognition, and (3) costs of xxxx. These could change our results xxx howerver Career advancement was small. Public recognition was the same. It is possible that the PRIZE solicitation treatment triggered xxx. 

Another potential limitations is the presence of confounding factors, limiting our causal interpretation of the results. Instead of being willing to contribute to the public good, employees may be motivated by the opportunity of advancing their career, or a gain in reputation. An extensive literature has indeed estimated the power of these incentives inside organizations [xxxx]. However, we demonstrate that these incentives are not only negligible in our setting, but also constant across the different solicitation treatments and, therefore, irrelevant for the interpretation of the results. First, promotions in academic hospitals are typically based on the number of publications, tenure, and professional training. Therefore, the likelihood of a career advancement through participating in the contest is of minor importance. Second, the winners received a public announcement during an organization-wide event and listing on the organization's website. This kind of publicity is an opportunity for a gain in reputation or peer recognition, but our solicitation treatments do not seem to affect it differently. To sum, while these other incentives may have contributed to the overall level of employee participation, we believe they have not altered the differences among solicitation treatments, and do not represent a limiting factor for our interpretation of the results. 

Staffs' poor understanding of the costs arising from winning the contest could explain their participation. In the same vein, a large experimental literature on contests [@dechenaux2014survey]  shows that similar misconception could lead to higher effort levels than predicted. In particular, those in the PRIZE treatment could have underestimated the costs of participating as the iPad mini accentuated the appeal of an immediate reward and diminish the costs of winning the contest and becoming involved in implementation. Across treatments, however, we find that most of the staff submitted a detailed proposal on their project when invited to do so. Although participants might have had incorrect beliefs about expected costs from winning, these are unlikely to explain the significant differences. 
 -->

Finally, our results have implications that extend beyond the specific organization under study. While the choice of focusing on health care workers may limit the generalizability of our results in some respect, it should be noted that in the US alone health care spending accounts for 17 percent of the GDP (in 2015). And, more generally, our study results are also directly applicable to a variety of other professions exposed to a public good dilemma (e.g., teachers, public servants, researchers). In all these settings, our study suggests that contests soliciting employee contributions and awarding an individual prize to the winning contribution appear an effective way to foster the internal provision of public goods inside organizations. 

<!-- 
The  contribution toward a public good among workers than currently acknowledged in the traditional tournament theory literature. The incentive effect of offering a prize for winning the contest interacts with pro-social motivations of workers to contribute to the public good. [xxxx]
 -->



<!-- 
~~~SO FAR~~~~

Our data show that offering a prize for winning submissions boosted participation by 85 percent without affecting the quality of the submissions. The effect was consistent across gender and job type. We posit that the allure of a prize, in combination with mission-oriented preferences, drove participation. 


These results were sensitive to the solicited person's gender. Women's participation was greater than men's when email solicitations emphasized patient care, controlling for profession. One possible explanation for this finding is that female staff may be more altruistic and more responsive to the issue of improving patient care than male staff. However, the existing economic literature on gender differences in altruistic preferences [see @croson2009gender] does not fully support this explanation. Another possible reason for women's greater responsiveness to patient care involves gender-based stereotypes, which are pervasive in health care organizations [@evans2002cautious]. Male staff could have judged the contribution of an innovation project towards patient care improvement as a female-typed activity. Similarly, @coffman2014evidence report that, in laboratory experiments, women were less likely to contribute ideas to groups when the topic falls in male-typed domains, e.g., sports, and vice versa.

An interesting non-finding is the lack of gender-based differences in the PRIZE treatment; we found that women's participation was equal to men's. An extensive literature in economics has revealed women's tendency to be risk-averse [@borghans2009gender] and a distaste for competition [@niederle2007women], suggesting that a contest for prize may discourage women's participation. In our experiment, however, women participated the most in the PRIZE treatment. We suspect that the unique characteristics of our subject pool (e.g., careers in health care) could have led to this finding.

While not observed, there could have been negative interactions between the prize incentive and the contest that encouraged staff members to contribute to public good by suggesting an organizational improvement opportunity. A negative interaction occurs when a particular incentive might crowd out the motive to contribute; for example, providing a self-serving incentive might negatively interact with a self-sacrificing activity and crowd out the motivation to participate in this activity. Experiments in the context of blood donations [@lacetera2013economic; @lacetera2014rewarding], or public "bads" in daycare pick-ups [@gneezy2000fine] indicate crowd-out effects. Pecuniary incentives may not have the same effect if in-kind gifts are used in place of currency [e.g., @kube2012currency], or if the setting already involves an employer-employee  relationship [e.g, @fehr1998gift]. 


Ulterior motivations such as the prospect of a promotion [@baker1994internal; @gibbs1995incentive], professional prestige, or peer recognition [@kosfeld2011getting; @blanes2011tournaments] could have propelled participation. However, the likelihood of career advancement through participating in the contest seems marginal as promotions in academic hospitals are typically based on the number of publications, tenure, and professional training. In addition, our email solicitations contained incentives that are fairly neutral to potential career advancement opportunities associated with the contest. Recognition for authors of winning proposals included announcement during a hospital-wide public event and listing on the hospital website. These opportunities to be acknowledged equally affected all potential participants. 



Finally, while the choice of focusing on health care workers may limit the generalizability of our results in some respect, it should be noted that in the US alone health care spending accounts for 17 percent of the GDP (in 2015) and, more generally, our study results are also directly applicable to a variety of other professions exposed to a public good dilemma (e.g., teachers, public servants, researchers). 



Our results have implications that extend beyond the specific organization under study. Using a contest for prizes appears to be a more profitable way for firms to encourage contribution toward a public good among workers than currently acknowledged in the traditional tournament theory literature. The incentive effect of offering a prize for winning the contest interacts with pro-social motivations of workers to contribute to the public good.

 -->
