---
title: "Incentives for Public Goods Inside Organizations: Field Experimental Evidence"

thanks: "Blasco: Harvard Institute for Quantitative Social Science, Harvard University, 1737 Cambridge Street, Cambridge, MA 02138 (email: ablasco@fas.harvard.edu). Jung: Harvard Business School, Soldiers Field, Boston, MA 02163 (email: oliviajung@gmail.com), Lakhani: Harvard Business School, Soldiers Field, Boston, MA 02163, and National Bureau of Economic Research (email: k@hbs.edu). Menietti: Harvard Institute for Quantitative Social Science, Harvard University, 1737 Cambridge Street, Cambridge, MA 02138 (email: mmenietti@fas.harvard.edu). We gratefully acknowledge the financial support of the MacArthur Foundation (Opening Governance Network), NASA Tournament Lab, and the Harvard Business School Division of Faculty Research and Development. This project would not have been possible without the support of Eric Isselbacher, Julia Jackson, Maulik Majmudar and Perry Band from the Massachusetts General Hospital's Healthcare Transformation Lab."

date: "Last updated: `r format(Sys.time(), '%d %B, %Y')`"

author: 
    - Andrea Blasco
    - Olivia S. Jung
    - Karim R. Lakhani
    - Michael Menietti

abstract: "We report results of a natural field experiment conducted at a medical organization that sought contribution of public goods (i.e., projects for organizational improvement) from its 1200 employees. Offering a prize for winning submissions boosted participation without affecting the quality of the submissions. The effect was consistent across gender and job type. We posit that the allure of a prize, in combination with mission-oriented preferences, drove participation. Using a simple model, we estimate that these preferences explain about a third of the magnitude of the effect. We also find that the opportunity of winning financial resources to lead one's own project implementation had a negative effect on participation. These results were sensitive to the solicited person's gender."

JEL: 
  - D23
  - H41
  - M52

keywords: 
  - innovation contest
  - free rider problem
  - social preferences
  - altruism
  - idea generation
  - organization of work

geometry: "left=1.5in, right=1.5in, top=1in, bottom=1in"
fontsize: 11pt
# fontfamily: tgbonum
# setspace: \doublespacing
endfloat: true
bibliography: refs.bib

output: 
  pdf_document:
    toc: true
    keep_tex: true
    latex_engine: pdflatex
    citation_package: natbib
    template: template.tex
#     pandoc_args: [
#     ]
---
    
```{r, echo=FALSE, warning=FALSE, message=FALSE}

# options
knitr::opts_chunk$set(
  cache=FALSE,
  echo=FALSE,
  message=FALSE,
  warning=FALSE,
  error=FALSE)
#   tidy=FALSE,
#   fig.width=5,
#   fig.height=5,
#   cache.path="cache/",

# required libraries
require(stargazer)
options(digits=3)

# Load data
load("../data-clean/mgh.RData")
capitalize <- function(x) x
percent <- function(x) round(100*x, 0)

# List of files
child_docs <- c('1_intro.Rmd'
							, '2_methods.Rmd'
							, '3_results.Rmd'
							, '4_discussion.Rmd'
)

# Stats
participants <- hc$num_ideas>0
evaluators <- hc$num_voted_ideas>0 # employees who voted

# Testing participation in evaluation
tab.eval <- xtabs(~ifelse(num_voted_ideas>0, 1,0)  + treatment,hc)
tab.eval.fisher <- fisher.test(tab.eval)

# Testing differences in quality
tab.quality.chisq <- chisq.test(ratings)

# Testing differences in content
index <- tapply(1:nrow(voting), voting$idea_id, head, n=1)
voting.cs <- voting[index, ] 
content.tab <- xtabs(~focus2 + treatment.proponent, voting.cs)
content.ftest <- fisher.test(content.tab, simulate.p.value=T, B=5e4)
```

```{r child=child_docs}
```

# References

